//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABetterTranslator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 650")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 20")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inputBox {
            get {
                return ((string)(this["inputBox"]));
            }
            set {
                this["inputBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string outputBox {
            get {
                return ((string)(this["outputBox"]));
            }
            set {
                this["outputBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int comboBoxFromLanguage {
            get {
                return ((int)(this["comboBoxFromLanguage"]));
            }
            set {
                this["comboBoxFromLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tabs {
            get {
                return ((int)(this["tabs"]));
            }
            set {
                this["tabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxBkUpDir {
            get {
                return ((string)(this["textBoxBkUpDir"]));
            }
            set {
                this["textBoxBkUpDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxLogFolderPath {
            get {
                return ((string)(this["textBoxLogFolderPath"]));
            }
            set {
                this["textBoxLogFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxRecursive {
            get {
                return ((bool)(this["checkBoxRecursive"]));
            }
            set {
                this["checkBoxRecursive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxBackupFilesBeforeTranslation {
            get {
                return ((bool)(this["checkBoxBackupFilesBeforeTranslation"]));
            }
            set {
                this["checkBoxBackupFilesBeforeTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public string MaxTranslateLen {
            get {
                return ((string)(this["MaxTranslateLen"]));
            }
            set {
                this["MaxTranslateLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string MaxThread {
            get {
                return ((string)(this["MaxThread"]));
            }
            set {
                this["MaxThread"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxItemsPerTransaltionRequest {
            get {
                return ((int)(this["comboBoxItemsPerTransaltionRequest"]));
            }
            set {
                this["comboBoxItemsPerTransaltionRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int comboBoxScreenVerbosityLevel {
            get {
                return ((int)(this["comboBoxScreenVerbosityLevel"]));
            }
            set {
                this["comboBoxScreenVerbosityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int comboBoxLogFileVerbosityLevel {
            get {
                return ((int)(this["comboBoxLogFileVerbosityLevel"]));
            }
            set {
                this["comboBoxLogFileVerbosityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxAddOriginalSrcTextToComment {
            get {
                return ((int)(this["comboBoxAddOriginalSrcTextToComment"]));
            }
            set {
                this["comboBoxAddOriginalSrcTextToComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxDeleteLangResxFilesBeforeTranslation {
            get {
                return ((bool)(this["checkBoxDeleteLangResxFilesBeforeTranslation"]));
            }
            set {
                this["checkBoxDeleteLangResxFilesBeforeTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxDispalyWarningPrompts {
            get {
                return ((bool)(this["checkBoxDispalyWarningPrompts"]));
            }
            set {
                this["checkBoxDispalyWarningPrompts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxOnStartupSetPreviousSessionLangSet {
            get {
                return ((bool)(this["checkBoxOnStartupSetPreviousSessionLangSet"]));
            }
            set {
                this["checkBoxOnStartupSetPreviousSessionLangSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAddSubLangToDefaultSet {
            get {
                return ((bool)(this["checkBoxAddSubLangToDefaultSet"]));
            }
            set {
                this["checkBoxAddSubLangToDefaultSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxDispalySummary {
            get {
                return ((bool)(this["checkBoxDispalySummary"]));
            }
            set {
                this["checkBoxDispalySummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int comboBoxDefaultLanguageSet {
            get {
                return ((int)(this["comboBoxDefaultLanguageSet"]));
            }
            set {
                this["comboBoxDefaultLanguageSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SelectedLanguageSet {
            get {
                return ((int)(this["SelectedLanguageSet"]));
            }
            set {
                this["SelectedLanguageSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection languageList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["languageList"]));
            }
            set {
                this["languageList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int comboBoxFromLang {
            get {
                return ((int)(this["comboBoxFromLang"]));
            }
            set {
                this["comboBoxFromLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int comboBoxToLang {
            get {
                return ((int)(this["comboBoxToLang"]));
            }
            set {
                this["comboBoxToLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxTextToTranslate {
            get {
                return ((string)(this["textBoxTextToTranslate"]));
            }
            set {
                this["textBoxTextToTranslate"] = value;
            }
        }
    }
}
