/* ***************************************************************************
 * Copyright © 2022 David Maisonave	(https://axter.com)	All rights reserved.
 * ***************************************************************************
 * The is free software. You can redistribute it and/or modify it under the 
 * terms of the MIT License. For more information, please see License file 
 * distributed with this package.
 * ***************************************************************************
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.DirectoryServices.ActiveDirectory;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;
using System.Net;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Security.Policy;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using ABI.System;
using GTranslate.Translators;
using Microsoft.VisualBasic.Devices;
using Microsoft.VisualBasic.Logging;
using static BrightIdeasSoftware.TreeListView;
using static System.Windows.Forms.LinkLabel;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.ProgressBar;


using static System.Windows.Forms.VisualStyles.VisualStyleElement.Rebar;


using static System.Windows.Forms.VisualStyles.VisualStyleElement.Tab;


using static System.Windows.Forms.VisualStyles.VisualStyleElement.TextBox;


using static System.Windows.Forms.VisualStyles.VisualStyleElement.ToolTip;


using static System.Windows.Forms.VisualStyles.VisualStyleElement;


using Windows.Devices.Radios;


using Windows.Foundation.Collections;

namespace ABetterTranslator
{
    static partial class LanguageCodes
    {
        public static readonly string[,] NativeNames =
        {   // This list is based on the following link: https://omniglot.com/language/names.htm
            #region NativeNames
            {"(Tai) Khün", "ᨴᩱ᩠ᨿᨡᩨ᩠ᨶ [táj kʰɯ̌ːn]"},
            {"’Auhelawa", "Kurada"},
            {"ǂ’Amkoe", "ǂʼAmkoe [ǂʼamkoe]"},
            {"Aari", "አፋን፡ኣሪ፡ (Áfan ārí)"},
            {"Abaza", "абаза бызшва (abaza bızšva)"},
            {"Abellen", "Ayta Abellen"},
            {"Abenaki", "Wôbanakiôdwawôgan"},
            {"Abkhaz", "Аҧсуа бызшәа (Apsua byzshwa) [apʰswa bɨzʃʷa], аҧсшәа (apsshwa) [apʰsʃʷ~ãa]"},
            {"Aborlan Tagbanwa", "Aborlan Tagbanwa"},
            {"Abui", "Abui tanga"},
            {"Acazulco Otomi", "Ndöö́ngüǘ yühǘ"},
            {"Acehnese", "Bahsa/Basa Acèh [bahsa at͡ʃeh], بهسا اچيه"},
            {"Achagua", "Achawa"},
            {"Achang", "Ngachang [ŋa˨˩tʂhaŋ˨˩]"},
            {"Acheron", "Acheron"},
            {"Achi", "Achi' [atʃiʔ]"},
            {"Acholi", "Lwo [lwo]"},
            {"Achuar-Shiwiar", "Achuár chícham"},
            {"Achumawi", "w·ó dis·i"},
            {"Adai(zan)", "Tenánat Hadéyas"},
            {"Adamaua Fulfulde", "Fulfulde"},
            {"Adyghe", "Адыгабзэ (Adygabzæ) [aːdəɣaːbza] КӀахыбзэ (K’axybzæ)"},
            {"Adzera", "Adzera"},
            {"Afaan Oromo", "ኦሮሞ፞, Afaan Oromoo [ɐfɑːn ɔrɔmoː]"},
            {"Afar", "Qafaraf"},
            {"Afrikaans", "Afrikaans [afriˈkɑːns]"},
            {"Aghul", "Агъул чӀал (Ağul ҫ̇al)"},
            {"Aguacateco", "Qa'yol"},
            {"Aguaruna", "Awajún"},
            {"Agutaynen", "Agutaynen"},
            {"Ahanta", "Ayɩnda"},
            {"A-Hmao", "ad Hmaob lul A-hmaos"},
            {"Ahom", "𑜒𑜑𑜪𑜨 (ahâm) [ahaːm]"},
            {"Ahtna", "'Atna' kenaege'"},
            {"Ainu", "アイヌ・イタㇰ / Ainu-itak [ˈainu iˈtak]"},
            {"Aiton", "တႝ ဢႝတွꩫ် (tai aiton) ဢႝတွꩫ် (aiton)"},
            {"Aja", "Adja"},
            {"Ajië", "Waawilûû"},
            {"Aka-Jeru", "Aka-Jeru"},
            {"Akan", "Akan"},
            {"Akatek", "K’anjob’al"},
            {"Akawaio", "Ka'pon"},
            {"Akhvakh", "Ашвaлъи мицIи (Ašvalʺi micˈi)"},
            {"Akkadian", "𒀝𒅗𒁺𒌑 (akkadû) 𒌵𒆠 (urik)"},
            {"Aklan", "Akeanon Binisaya nga Akeanon Inakeanon"},
            {"Akurio", "Akuriyó"},
            {"Alabama", "Albaamo innaaɬiilka"},
            {"Alasha (Mongolian)", "ᠠᠯᠠᠱᠠᠨ ᠠᠮᠠᠨ ᠠᠶᠠᠯᠭᠤ Alašan aman ayalğu"},
            {"Albanian", "shqip [ʃc͡çip] gjuha shqipe [ɟ͡ʝuha ˈʃc͡çipɛ]"},
            {"Aleut", "Unangam Tunuu [uˈnaŋam tuˈnuː] Уна́ӈам тунуу́ унаӈан умсуу"},
            {"Algonquin", "Anicinàbemowin Anishinàbemiwin"},
            {"Alsatian", "Ëlsässisch Elsässerditsch"},
            {"Altay", "алтайдыҥ тил (altajdyng til) алтай тил (altaj til)"},
            {"Alur", "Dho-Alur [d̟ɔ.a.lur]"},
            {"Alutiiq", "Sugpiaq"},
            {"Alyawarr", "Alyawarr"},
            {"Alyutor", "Нәмәлъу (Nəməlʔu) [nəməlʔu]"},
            {"Amahuaca", "Amahuaca"},
            {"Amami (Ōshima)", "ユムタ (yumuta) [jumuθa] シマユムタ (shimayumuta) [simaˈjumuθa] ヤタトグチ (yamatoguchi) [ˈjamaθoɡuci]"},
            {"Amarakaeri", "Amarakaeri"},
            {"Amarasi", "Amarasi"},
            {"Ambala", "Ayta Ambala"},
            {"Ambel", "galí Ambél (Ambel language) galí Mayá (Ma’ya language) galí (anguage)"},
            {"Amdo Tibetan", "ཨ་མདོའི་སྐད་ (A-mdo'i skad)"},
            {"Amele", "Sona"},
            {"Amharic", "ኣማርኛ (Amarəñña) [amarɨɲːa]"},
            {"Amis", "Pangcah [paŋt͡saʜ]"},
            {"Ancash Quechua", "Anqas Qichwa"},
            {"Andi", "къIaваннаб мицци (qwavannab miċċi)"},
            {"Andoa", "Andoa"},
            {"Angami", "Angami"},
            {"Angika", "अंगिका (āṅgikā) [ä̃ːɡɪka]"},
            {"Anindilyakwa", "Amamalya Ayakwa"},
            {"Anuki", "Anuki"},
            {"Anutan", "te taranga paka-Anuta"},
            {"Anyin", "Anyin"},
            {"Apache (Western)", "Ndéé Ndee biyáti’ Nnee biyáti’"},
            {"Apatani", "Tanw Aguñ"},
            {"Apma", "Apma"},
            {"Apurinã", "Popikariwakori"},
            {"Arabela", "Tapweyokwaka"},
            {"Arabic (Algerian)", "(daridja) درجة, الدارجة العربيّة الجزائريّة"},
            {"Arabic (Chad)", "(tšādiya) تشادية"},
            {"Arabic (Cypriot)", "Σάννα, Sánna"},
            {"Arabic (Egyptian)", "[ˈʕɑrɑbi] ('arabi) عربى [el.ʕæmˈmejjæ l.mɑsˤˈɾejjɑ] العاميه المصريه (aamiyya) عامية "},
            {"Arabic (Gulf)", "[xɑˈliːdʒi] (ḵalījī) خليجي‎ (il-lahja il-ḵalījīya) اللهجة الخليجية [(ɪ)lˈlæhdʒæ lxæˈliːdʒiːjæ]"},
            {"Arabic (Hasaniya)", "Ḥassānīya, حسانية"},
            {"Arabic (Hejazi)", "حجازي [ħɪˈdʒaːzi / ħe̞ˈdʒaːzi] Ḥijāzi=libnēne (lubnāniyy) لُبْنَانِي‎,  ʿarabe libnēne (ʿarabiyy lubnāniyy) لبناني عربي"},
            {"Arabic (Lebanese)", "(lībī) ليبي‎"},
            {"Arabic (Modern Standard)", "العربية الفصحى [al ʕaraˈbijja lˈfusˤħa] (al-ʻArabīyah al-Fuṣḥā)"},
            {"Arabic (Moroccan)", "[ddæɾiʒæ] (darija) الدارجة, الدارجة المغربية"},
            {"Arabic (Najdi)", "اللهجة النجدية"},
            {"Arabic (Syrian)", "اللهجة العربيّة السورىّة"},
            {"Arabic (Tunisian)", "(tounsi) تونسي"},
            {"Aragonese", "Aragonés [aɾaɣoˈnes]"},
            {"Arakanese", "ရခိုင်ဘာသာ (ra.hkuing bhasa) [ɹəkʰàɪɴ bàθà]"},
            {"Araki", "Araki"},
            {"Aramaic", "(arāmāyā) ܐܪܡܝܐ, ארמיא, 𐡀𐡓𐡌𐡉𐡀"},
            {"Aranese", "Aranés"},
            {"Arapaho", "Hinónoʼeitíít"},
            {"Arawak", "Lokono"},
            {"Arbëresh", "arbërisht"},
            {"Archi", "аршаттен чIат (aršatten č’at)"},
            {"Are", "Mukawa"},
            {"Argobba", "ዓርጎባ (arıgogä)"},
            {"Arikara", "Sáhniš"},
            {"Aringa", "Ãriṇ̃gã"},
            {"Armenian", "Հայերէն (hayeren) [hɑjɛˈɾɛn] արևելահայերեն (arevelahayeren) - Eastern Armenian արեւմտահայերէն (arevmdahayeren) - Western Armenian"},
            {"Aromanian", "Armâneaşti"},
            {"Arrernte", "Arrernte angkentye"},
            {"Arta", "Arta"},
            {"Arvanitic", "αρbε̰ρίσ̈τ (arbërisht) [aɾbəˈɾiʃt]"},
            {"Asháninka", "Asháninka"},
            {"Ashéninka", "Ashéninka"},
            {"Assamese", "অসমীয়া (asamiya) [ɔxɔmija]"},
            {"Assiniboine", "Nakoda"},
            {"Assyrian, Neo-Assyrian", "(Lišānā Āṯûrāya) ܐܵܬ݂ܘܼܪܵܝܲܐ ܠܸܫܵܢܵܐ"},
            {"Asturian", "Asturianu"},
            {"Atayal", "Atayal"},
            {"Ateso", "Ateso [atɛsɔ]"},
            {"Athpare", "आठपहरिया‎ (āṭhapahariyā)"},
            {"Atikamekw", "Atikamekw"},
            {"Atong", "Atong"},
            {"Austral", "reo Tuha'a pae"},
            {"Avar", "магІарул мацІ (Maǥarul macʼ) [maʕarul mat͡sʼ] Авар мацӏ (Awar macʼ) [awar mat͡sʼ]"},
            {"Avestan", "𐬛𐬍𐬥 𐬛𐬀𐬠𐬌𐬫𐬭𐬵"},
            {"Avokaya", "Avokaya"},
            {"Awa Pit", "Awa Pit"},
            {"Awadhi", "अवधी, 𑂃𑂫𑂡, 𑂃𑂫𑂡𑂲𑂲 (Avadhī) [əʋ.d̪ʱiː]"},
            {"Awara", "Awara"},
            {"Awing", "Mbwe'wi"},
            {"Awngi", "አውጚ (awngi) [ˈawŋi]"},
            {"Aymara", "aymar aru [ajmaɾ ˈaɾu]"},
            {"Äynu", "[ɛjˈnu]) (Äynú) ئهﻳنوُ"},
            {"Azerbaijani", "Azərbaycan dili, Азәрбајҹан дили, آذربایجان دیلی‎  [ɑːzæɾbɑjˈdʒɑn diˈli]"},
            {"Babine-Witsuwit'en", "Nedut'en, Witsuwit'en"},
            {"Badaga", "படுக, ಬಡಗ (badaga)"},
            {"Bade", "gàbàden"},
            {"Bagatha", "Bagatha"},
            {"Bagri", "बागड़ी (bāgṛī)"},
            {"Bagvalal", "Багвалазул мицӀцӀ (Bagvalazul mic’c’)"},
            {"Bai", "Baip‧ngvp‧zix"},
            {"Bajaw", "Bajo"},
            {"Baka", "Baka"},
            {"Bakairi", "Kurâ"},
            {"Balangao", "Balangao"},
            {"Balanta-Ganja", "Balanta-Ganja"},
            {"Balanta-Kentohe", "Kəntɔhɛ"},
            {"Balinese", "Basa Bali (ᬩᬲᬩᬮᬶ) Bhāṣa Bali (ᬪᬵᬱᬩᬮᬶ)"},
            {"Balkar", "Къарачай-Малкъар тил (Qaraçay-Malqar til) Таулу тил (Tawlu til)"},
            {"Balti", "སྦལ་འཐུས་ (balti) بلتی"},
            {"Baluchi / Balochi", "(balòci) بلوچی"},
            {"Bambara", "Bamanankan [bamanãkã] ߓߊߡߊߣߊ߲ߞߊ߲"},
            {"Bambassi / Northern Mao", "Màwés Aasʼè [ma˩we˥s aːsʔe˩]"},
            {"Bamum", "Shüpamom"},
            {"Bandial", "Banjaal"},
            {"Baniwa of Guainía", "Ayane"},
            {"Baniwa", "Tapuya"},
            {"Banjarese / Banjar", "Bahasa Banjar [bahasa bandʒar] بهاس بنجر"},
            {"Bantawa", "Bantawa"},
            {"Bantayanon", "Bantayanon"},
            {"Bantik", "Bantik"},
            {"Bantoanon", "Binisaya, Bisaya"},
            {"Baoulé", "Baoulé"},
            {"Barai", "Barai"},
            {"Barbareño", "Pʼatna"},
            {"Bardi", "Bardi"},
            {"Barein", "Barayin"},
            {"Bari", "Karo, Kutuk"},
            {"Bariba", "baatɔnum"},
            {"Barin (Mongolian)", "ᠪᠠᠭᠠᠷᠢᠨ (Bağarin) ᠪᠠᠭᠠᠷᠢᠨ ᠠᠮᠠᠨ ᠠᠶᠠᠯᠭᠤ (Bağarin aman ayalğu)"},
            {"Bartangi", "Bartangi ziv"},
            {"Basaa", "ɓasaá ɓàsàa"},
            {"Bashkir", "Башҡортса (Bashqortsa) [bɑʃˈqortsɑ] Башҡорт теле (Bashqort tele) [bɑʃˈqort tɘˈlɘ]"},
            {"Basque", "Euskara [eus̺ˈkaɾa]"},
            {"Bassa", "𖫢𖫧𖫳𖫒𖫨𖫰𖫨𖫱, Ɓǎsɔ́ɔ̀ [ɓa˨˧sɔ˦ɔ˨]"},
            {"Bassari", "o-niyan [ɔnijan]"},
            {"Batak", "Batta"},
            {"Batsbi", "ბაცბურ მოტტ (Batsbä Moț)"},
            {"Baure", "Baure"},
            {"Bavarian", "Boarisch, Bairisch [ˈbɔɑ̯rɪʃ]"},
            {"Baybayanon", "Baybayanon"},
            {"Beja", "Bidhaawyeet, Tubdhaawi, بڈاويێت, تُبڈاوِ"},
            {"Belarusian", "Беларуская мова (Bielaruskaja mova) [bʲelaˈruskaja ˈmova]"},
            {"Belhare / Athpahariya", "आठपहरिया (athapahariya)"},
            {"Beli", "’Bëlï"},
            {"Bella Coola / Nuxalk", "ItNuxalkmc"},
            {"Bemba", "ichiBemba"},
            {"Bench", "bèntʂ nòn"},
            {"Bengali", "বাংলা (bangla) [ˈbaŋla]"},
            {"Berber (Tamazight)", "Tamaziɣt"},
            {"Betawi", "Bahasa Betawi"},
            {"Betedaloa", "Bété"},
            {"Bezhta", "бежкьалас миц (bežƛʼalas mic) beƶⱡʼalas mic [ˈbeʒt͡ɬʼɑlɑs mit͡s]"},
            {"Bhili", "भीली / ભીલી (bhīlī)"},
            {"Bhojpuri", "भोजपुरी / 𑂦𑂷𑂔𑂣𑂳𑂩𑂲 (bhojpurī) [bʱoʤpuriː]"},
            {"Bhumij", "भूमिज / ଭୂମିଜ / ভূমিজ (bhūmij) [bʱumid͡ʒ]"},
            {"Biete", "Biete"},
            {"Bikol  (Central)", "Bikol Sentral"},
            {"Bilaspuri", "बिलासपुरी, 𑚠𑚮𑚥𑚭𑚨𑚞𑚱𑚤𑚯 (bilāsapurī) [bilaːsapuriː] कहलूरी, 𑚊𑚩𑚥𑚱𑚤𑚯 (kahlūrī) [kahluːriː]"},
            {"Biloxi", "Tanêksąyaa ade"},
            {"Bilua", "Bilua"},
            {"Bima", "Nggahi Mbojo"},
            {"Bininj Kunwok", "Bininj Kunwok"},
            {"Binukid", "Binukid"},
            {"Birifor (Southern)", "Birfoɔr"},
            {"Bishnupriya Manipuri", "বিষ্ণুপ্রিয়া মণিপুরী ঠার (bisnupriyā mônipurī thār) ইমার ঠার (imār thār)"},
            {"Bislama", "Bislama [bislaˈma]"},
            {"Bisu", "Bisu"},
            {"Blackfoot", "Siksiká / ᓱᖽᐧᖿ [siksiká]"},
            {"Blagar", "Blagar"},
            {"Blin", "ብሊና (b(ɨ)lina), ብሊን (b(ɨ)lin)"},
            {"Bodo", "बर' / बड़ (boṛo) [bɔɽo]"},
            {"Bokar", "Bokar"},
            {"Bolinao", "Binu-Bolinao"},
            {"Bolyu", "Pɔ₃₃lju₁₃"},
            {"Bonggi", "Bonggi"},
            {"Bongo", "Bongo"},
            {"Bontoc", "Finallig"},
            {"Bora", "Bora"},
            {"Bosnian", "bosanski, босански, بۉسانسقى, bosanski jezik"},
            {"Botlikh", "Буйхалъи мицӏцӏи (Bujxałi mic’c’i)"},
            {"Botolan", "Botolan"},
            {"Bouyei", "Haasqyaix"},
            {"Brahui", "[brəˈhuːi] (Bráhuí) براوی"},
            {"Braj", "ब्रज भाषा (braj bhāsā)"},
            {"Breton", "Brezhoneg [bʁeˈzõːnɛk / brəhõˈnek]"},
            {"Bribri", "se'ie"},
            {"Budukh", "Будад мез (budad mez)"},
            {"Bugan", "Pakan [pə˥˥ka̤n˧˧]"},
            {"Bugis", "Basa Ugi / ᨅᨔ ᨕᨘᨁᨗ"},
            {"Bugkalot", "Bogkalot"},
            {"Buglere", "Buglere"},
            {"Buhid", "ᝊᝓᝑᝒ (buhid)"},
            {"Buhutu", "Buhutu"},
            {"Bukid", "Binukid [binukid]"},
            {"Bukusu", "Lubukusu"},
            {"Bulgarian", "Български (bǎlgarski) [ˈbɤɫɡɐrski]"},
            {"Bulu", "Bulu"},
            {"Bundjalung", "Yugambeh-Bundjalung"},
            {"Bungku", "Bungku [buᵑku]"},
            {"Bunun", "Bunun"},
            {"Burmese / Myanmar", "မြန်မာစကား (mramazaga) [mjəmà zəɡá] မြန်မာစာ (mranmaza) [mjəmàzà] မြန်မာဘာသာ (mranmabhasa) [mjəmà bàðà]"},
            {"Burushaski", "بروشسکی‎ (burū́šaskī)"},
            {"Buryat", "буряад хэлэн (buryaad xelen), ᠪᠤᠷᠢᠶᠠᠳ (buriyad) [ˈburɪɑd]"},
            {"Busa", "Bisã"},
            {"Bushi", "Shibushi Kibushi"},
            {"Butuanon", "Butuanon"},
            {"Bwaidoka", "Bwaidoka"},
            {"Cabécar", "Cabécar"},
            {"Caddo", "Has-sii'-nay"},
            {"Cajamarca Quechua", "Kashamarka qichwa Kashamarka Runashimi"},
            {"Calamian Tagbanwa", "Tinagbanwa / ᝦᝲᝨᝪᝯ"},
            {"Caló", "caló [kaˈlo̞]"},
            {"Caluyanon", "Caluyanon"},
            {"Cambodian (Khmer)", "ខ្មែរ (khmae) [kʰmae] ភាសាខ្មែរ (phiăsaa khmae) [pʰiə.ˈsaː kʰmae] ខេមរភាសា (kheemaʾraʾ phiăsaa) [kʰeː.maʔ.raʔ pʰiə.ˈsaː]"},
            {"Canaanite", "Canaanite"},
            {"Candoshi-Shapra", "Candoshi-Shapra"},
            {"Cape Verdean Creole", "Kriolu"},
            {"Capiznon", "Kapisnon"},
            {"Caquinte", "Caquinte"},
            {"Car", "Pū"},
            {"Carian", "Carian"},
            {"Carib", "Kari'nja"},
            {"Carijona", "Tsahá"},
            {"Carolinian", "Refalúwasch"},
            {"Carrier", "Dakeł, ᑕᗸᒡ [tákʰɛɬ]"},
            {"Casiguran Dumagat Agta", "Casiguran Dumagat Agta"},
            {"Catalan", "català [kətəˈla]"},
            {"Cayuga", "Goyogo̱hó:nǫ’"},
            {"Cebuano", "Binisaya"},
            {"Celtiberian", "Celtiberian"},
            {"Central Sinama", "Bahasa Sinama Bajau Badjao"},
            {"Ch’ol", "Lakty’añ"},
            {"Chagatai", "(jağatāy) جغتای"},
            {"Chaha", "ቸሃ (čehā / čexā)"},
            {"Chakhar (Mongolian)", "ᠴᠠᠬᠠᠷ (čaqar) ᠴᠠᠬᠠᠷ ᠠᠮᠠᠨ ᠠᠶᠠᠯᠭᠤ (čaqar aman ayalγu)"},
            {"Chakma", "Changma Vaj Changma Kodha"},
            {"Chakosi", "Anufo"},
            {"Chaldean Neo-Aramaic", "(Kaldāyâ) ܟܠܕܝܐ  (Sōreth) ܣܘܼܪܲܝܬ"},
            {"Cham", "ꨌꩌ (Cam) ꨀꨇꩉ ꨌꩌ (Akhar Cam)"},
            {"Chamalal", "чамалалдуб мичӀчӀ"},
            {"Chambeali", "चम्बयाळी / 𑚏𑚢𑚶𑚠𑚣𑚭𑚥𑚷𑚯 (chambayāḷī) [c͡çʰəmbəjɑːɭiː]"},
            {"Chami", "Ẽbẽra [ẽbẽra]"},
            {"Chamicuro", "Kana"},
            {"Chamling", "चाम्लिङ् (cāmliṅ) [camliŋ]"},
            {"Chamorro", "Finuʼ Chamoru [finuʔ t̪͡s̪æmoɾu] Finoʼ CHamoru [finoʔ t̪͡s̪æmoɾu],"},
            {"Chang", "Mochungrr"},
            {"Cha'palaa", "Cha'palaa"},
            {"Chatino", "chaqF tnyaJ"},
            {"Chavacano", "Chavacano"},
            {"Chayahuita", "Paranapura Shawi"},
            {"Chechen", "Нохчийн мотт (Noxchiin mott)"},
            {"Chelkan", "куу (kuu) чалканду (čalkandu)"},
            {"Cherokee", "ᏣᎳᎩ, Tsalagi [dʒalaˈɡî] ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ, Tsalagi Gawonihisdi [dʒalaˈɡî ɡawónihisˈdî])"},
            {"Cheyenne", "Tsėhesenėstsestotse"},
            {"Chhantyal", "छन्त्याल (chanytyāl) [cʰəntjal]"},
            {"Chhattisgarhi", "छत्तीसगढ़ी‎ (chhattīsgarhī) ଲରିଆ (lariā) ଛତିଶଗଡ଼ି (chatiśagaḍi)"},
            {"Chicahuaxtla Triqui", "Nânj nì’ïn"},
            {"Chichewa", "Chicheŵa [ʧiʧeβa]"},
            {"Chickasaw", "Chikashshanompa' [tʃikaʃːanompaʔ]"},
            {"Chilcotin", "Tŝinlhqut’in"},
            {"Chinanteco", "Chinanteco"},
            {"Chinese (Cantonese)", "广州话 [廣州話] (Gwóngdūng wá) [kʷɔŋ˧˥ tʊŋ˥ wa˧˥], 广东话 [廣東話] (Gwóngjāu wá) [kʷɔŋ˧˥ ʦɐu˥ wa˧˥], 粤语 [粵語] (Yuhtyúh) [jyːt̚˧˥ ju˧˥]"},
            {"Chinese (Dungan)", "Хуэйзў йүян, Huejzw jyjan, حُوِظُ يُوْيًا 回族語言 [xwɛi˨˦tsu˨˦ jy˨˩˦jɑn˨˦]"},
            {"Chinese (Fuzhounese)", "福州話 (Hók-ciŭ-uâ) [huʔ˨˩ tsju˥˧ wɑ˨˦˨] 福州語 (Hók-ciŭ-ngṳ̄), 平話 (Bàng-uâ)"},
            {"Chinese (Gan)", "赣语 (Gon ua), 江西话 (Jiāngxī huà)"},
            {"Chinese (Hakka)", "客家话 [客家話] (Hak-kâ-fa /Hak-kâ-va)"},
            {"Chinese (Jian'ou)", "建甌事 (Gṳ̄̄ing-é-dī) [kuiŋ˧ ɪ˥˦ ti˦]"},
            {"Chinese (Mandarin)", "普通话 [普通話] (Pǔtōnghuà) [phu˩˧ thɔŋ˥ hua˥˩] 国语 [國語] (Guóyǔ) [kuɔ˩˥ y˧˩˥] 华语 [華語] (Huáyǔ) [hua˩˥ y˧˩˥] 汉语 [漢語] (Hànyǔ) [han˥˩ y˧˩˥]"},
            {"Chinese (Puxian)", "溫州話 (Pô-sing-uā)"},
            {"Chinese (Shanghainese)", "上海话 [上海話] (Zaonhegho) 上海闲话 [上海閒話] (Zaonhe-ghegho) [z̥ɑ̃̀héɦɛ̀ɦò] 沪语 [滬語] (Wu nyu) [ɦùɲý]"},
            {"Chinese (Taiwanese)", "臺灣話 / Tâi-oân-ōe / Tâi-uân-uē 臺語 / Tâi-gí / Tâi-gú [tai˧ gi˥˩ / tai˧˩ gu˥] 福佬 / Ho̍h-ló 閩南語 / Bân-lâm-gí"},
            {"Chinese (Teochew)", "潮州话 (Diê⁵ziu¹ uê / Dio⁵ziu¹ uê)"},
            {"Chinese (Weitou)", "圍頭話 [围头话] (Wai²dau²waa²)"},
            {"Chinese (Wenzhounese)", "溫州話 [溫州話] (Iu¹ ciou¹ hhuo²)"},
            {"Chinese (Wu)", "吴语 [吳語] (ngu¹ ngiu²)"},
            {"Chinese (Xiang)", "湘语 (sion ny / xia y) [siɔ̃⁴⁴.ny⁴² / ɕiæ̃³³.y⁴³] 湖南语"},
            {"Chinese (Yue)", "粤语 [粵語] (Yuhtyúh) [jyːt̚˧˥ ju˧˥]"},
            {"Chinook Jargon", "chinuk wawa"},
            {"Chinook", "Tsinúk"},
            {"Chipewyan", "Dënesųłıné, ᑌᓀᓱᐠᑦᕄᓀ"},
            {"Chippewa", "Ojibwemowin"},
            {"Chiquihuitlán Mazatec", "Hne naja"},
            {"Chitimacha", "Čitimaaša"},
            {"Chittagonian", "চাটগাঁইয়া (caṭgãiya) [saʈɡãija] চাটগাঁইয়া বুচি (caṭgãiya buli) [saʈɡãija buli] (siṭāiṅgā) سٹاعڠگا"},
            {"Chiwere", "Báxoje-Jíwere-Ñútˀachi"},
            {"Choctaw", "Chahta' Chahta Anumpa"},
            {"Chokwe", "Ucokwe"},
            {"Chontal Maya", "Yoko t’an"},
            {"Chorti", "Ch'orti'"},
            {"Chrau", "Chrau"},
            {"Chru", "Chru"},
            {"Chuj", "Koti’ [kotiʔ]"},
            {"Chukchansi", "Chukchansi"},
            {"Chukchi", "Ԓыгъоравэтԓьэн йиԓыйиԓ (Ḷyg”oravėtḷ’en jiḷyjiḷ) [ʎəɣʔoɻaβetʎʔen jiʎəjiʎ]"},
            {"Chulym", "ӧс тили (ös tili) [øs tilɪ]"},
            {"Chuukese / Trukese", "Chuuk [ʈʂu.uk]"},
            {"Chuvash", "Чӑвашла (Căvashla) [tɕəʋaʃˈla]"},
            {"Cia-Cia", "Bahasa Ciacia, 바하사 찌아찌아"},
            {"Cimbrian", "Tzimbrisch"},
            {"Cipu", "Tə-Səgəmuk"},
            {"Coatzospan Mixtec", "Ntudu tuhun davi Tu’un davi"},
            {"Cocopah", "Kwikapa"},
            {"Coeur d'Alene", "Snchitsu'umshtsn"},
            {"Cofán", "A'ingae"},
            {"Comanche", "nʉmʉ tekwapʉ̱"},
            {"Comorian", "Shikomori"},
            {"Comox", "Salhulhtxw"},
            {"Copala Triqui", "Xnaꞌánj nu̱ꞌ"},
            {"Coptic", "ⲘⲉⲧⲢⲉⲙ̀ⲛⲭⲏⲙⲓ"},
            {"Cora", "naáyarite"},
            {"Cornish", "Kernewek [kəɾˈnuːək]"},
            {"Corsican", "corsu [ˈkorsu] [ˈkɔrsu] lingua corsa [ˈliŋɡwa ˈkorsa]"},
            {"Cree (Moose)", "ᐃᓕᓖᒧᐎᓐ / ililîmowin"},
            {"Cree (Plains)", "ᓀᐦᐃᔭᐍᐏᐣ / nēhiyawēwin"},
            {"Cree (Swampy)", "ᓀᐦᐃᓇᐍᐏᐣ / nêhinawêwin"},
            {"Cree (Woods)", "ᓃᐦᐃᖬᐑᐏᐣ / nīhithawīwin"},
            {"Creek", "Mvskoke"},
            {"Crimean Tatar", "къырымтатар тили (qırımtatar tili) къырым тили (qırım tili)"},
            {"Croatian", "hrvatski [xř̩ʋaːtskiː]"},
            {"Crow", "Apsáalooke [ə̀ˈpsáːɾòːɡè] Apsáalooke aliláau"},
            {"Cubeo", "pãmié"},
            {"Cumbric", "Cumbraek"},
            {"Curripaco", "Kurripako / Wakue"},
            {"Cuyonon", "Cuyonon"},
            {"Czech", "čeština [ˈtʃɛʃcɪna] český jazyk"},
            {"Dadibi", "Dadibi"},
            {"Daga", "Daga"},
            {"Dagaare", "Dagaare"},
            {"Dagbani", "Dagomba"},
            {"Dakota", "Dakhóta Dakhótiyapi [daˈkʰotijapi] Dakȟótiyapi [daˈqˣotijapi]"},
            {"Dalmatian", "langa Dalmata"},
            {"Dananshan Miao", "Hmongb Drout Raol"},
            {"Dane-zaa (Beaver)", "Dane-zaa Ẕáágéʔ (ᑕᓀᖚ ᖚᗀᐥ) [dɜne za z̪a˥keʔ˥]"},
            {"Dangaléat", "daŋla [daŋla]"},
            {"Danish", "dansk [ˈtænˀsk]"},
            {"Danwar", "दनुवारी (danuwārī) [d̪ənuwaːrɪː]"},
            {"Dargwa", "дарган мез (dargan mez)"},
            {"Dari", "[dæˈɾiː] (Darī) درى"},
            {"Daur", "ᡩᠠᡤᡠᠷ ᡠᠰᠸ (Dagür üsw)"},
            {"Dawan", "Uab Metô"},
            {"Daza", "Dazaga"},
            {"Deg Xinag", "Degexit'an"},
            {"Dehong Dai / Tai Nuea", "ᥖᥭᥰᥖᥬᥳᥑᥨᥒᥰ (Tai2 Lə6)"},
            {"Dena’ina", "Dena’ina Qenaga, Dena’inaq’"},
            {"Dengebu", "Dagik"},
            {"Desiya", "ଦେଶିଆ (deśiā) [desia]"},
            {"Dhao", "Dhao"},
            {"Dhatki", "धाटकी ڍاٽڪي (dhātkī) धत्ती ڍاٽي (dhattī) थारी ٿَري (thārī)"},
            {"Dhimal", "धिमाल (dhimāl) [dʱimaːl]"},
            {"Dholuo (Luo)", "Dholuo"},
            {"Dhundari", "ढूंढाड़ी ḍhūṃḍhāṛĩ [ɖʱũɖʱaɾi]"},
            {"Dhurwa", "ପରଜି / धुरवा (durawā) [durʌwaː]"},
            {"Dhuwal", "Dhuwal"},
            {"Digaro Mishmi", "Taraon"},
            {"Digo", "Chidigo [ʧidiɡɔ]"},
            {"Dinka", "Thuɔŋjäŋ"},
            {"Dioula", "Julakan [ɟulakan] ߖߎ߬ߟߊ߬ߞߊ߲"},
            {"Ditidaht", "diid̓iitidq"},
            {"Diyari", "Rdiyarrhi yawarrha"},
            {"Dizin", "ዲዚኖግ"},
            {"Djinang", "Djinang [ɟinba]"},
            {"Djinba", "Djinba [ɟinaŋ]"},
            {"Dogri", "डोगरी (ḍogrī) ڈوگرى"},
            {"Dogrib (Tłı̨chǫ)", "Tłı̨chǫ Yatıì"},
            {"Dolgan", "Дулҕан (Dulğan) Һака (Haka)"},
            {"Domari", "Dômarî, דּוֺמָרִי, دٛومَرِي"},
            {"Dominican Creole", "kwéyòl [kwejɔl]"},
            {"Dongotono", "Dongotono"},
            {"Doteli / Dotyali", "डोटेली (doṭelī) [doʈeliː] डोट्याली‎ (doṭyālī) [doʈjaːliː]"},
            {"Drehu", "Deʼu"},
            {"Drung", "Tvrung kvt"},
            {"Duala", "Duálá"},
            {"Dupaningan", "Dupaningan"},
            {"Duri", "Masenrempulu"},
            {"Dusun", "Dusun"},
            {"Dutch", "Nederlands [ˈneːdərlɑnts]"},
            {"Dzongkha (Bhutanese)", "རྫོང་ཁ་ (dzongkha) [dzòŋkʰɑ́]"},
            {"Edo", "Ẹ̀dó"},
            {"Efik", "Efik"},
            {"Ekoka !Kung", "Ekoka !Kung"},
            {"Elamite", "Elamite"},
            {"Elfdalian", "övdalsk, övdalską"},
            {"Emae", "Fakamakata"},
            {"Emberá (Northern)", "Emberá"},
            {"Emilian-Romagnol", "emiliân-rumagnol"},
            {"Ende-Li'o", "Li'o"},
            {"Enets", "Онаь базаан (Onei baza)"},
            {"English", "English [ˈɪŋɡlɪʃ]"},
            {"Eperara", "Epéna Pedée"},
            {"Erromintxela", "Erromintxela"},
            {"Erzya", "эрзянь кель (erzyan' kel')"},
            {"Esperanto", "Esperanto [espeˈranto]"},
            {"Estonian", "eesti keel [ˈeːsti ˈkeːl]"},
            {"Eton", "Ìtón"},
            {"Etruscan", "mekh Rasnal"},
            {"Even", "эвэды торэн (evedy toren)"},
            {"Evenki", "Эвэды̄ турэ̄н (Evedȳ turēn) ᠧᠠᠩᠬᠢ"},
            {"Ewe", "Eʋegbe"},
            {"Ewondo", "Ewondo"},
            {"Extremaduran", "estremeñu [ehtːɾeˈmeɲʊ]"},
            {"Eyak", "dAXunhyuuga’"},
            {"Fala", "A Fala"},
            {"Faliscan", "Faliscan"},
            {"Fanagalo", "Fanakalo"},
            {"Fang", "Faŋ Paŋwe"},
            {"Fante", "Mfante"},
            {"Faroese", "færøsk sprog føroyskt mál [ˈføːɹɪst mɔaːl]"},
            {"Fiji Hindi", "Hindustani"},
            {"Fijian", "Na vosa vaka-Viti"},
            {"Finnish (Romani) Kalo", "kaalengo tšimb [ˈkaːleŋːo ˈt͡ʃimp]"},
            {"Finnish", "suomi [ˈsuo̯mi] suomen kieli [ˈsuo̯meŋ ˈkie̯li]"},
            {"Flemish", "Vlaams Vlaams-Nederlands Belgisch-Nederlands"},
            {"Folkspraak", "Folkspraak"},
            {"Fon", "fɔ̀ngbè [fɔ̃̀ɡ͡bē]"},
            {"Fox", "Meshkwahkihaki (Fox/Meskwaki dialect) Thâkiwâtowêweni (Sauk dialect)"},
            {"Frafra", "ninkãrɛ gʋrnɛ fãrfãre"},
            {"Franco-Provençal", "Arpitan patouès, Arpetan"},
            {"French Guianese Creole", "Guyanais, Patwa"},
            {"French", "français [fʁɑ̃sɛ]"},
            {"Frisian (East)", "Ōstfräisk"},
            {"Frisian (North)", "Nuurđfriisk (Sylt) nuurdfresk (Föhr/Amrum) Noorfriisk (Heligoland) nordfreesk (Wiedingharde/Halligen) nordfrasch (Mooring) nordfräisch (Karrharde) noordfreesch (Central Goesharde)"},
            {"Frisian (Saterland)", "Seeltersk"},
            {"Frisian (West)", "Frysk [frisk] Westerlauwersk Frysk Westerlauwers Fries"},
            {"Friulian", "furlan marilenghe"},
            {"Fula(ni)", "Fulfulde"},
            {"Fur", "bèle fòòr fòòraŋ bèle"},
            {"Futuna-Aniwa", "Fotuna-Anewa"},
            {"Futunan", "Fakafutuna"},
            {"Fuyu Kyrgyz", "Fuyü Gïrgïs"},
            {"Gǀui", "Glui"},
            {"Ga", "Gã [ɡã]"},
            {"Gadaba", "Gadaba"},
            {"Gaddang", "Gaddang"},
            {"Gaddi", "𑚌𑚛𑚯, गदी (Gaddi) 𑚌𑚛𑚊𑚯, गदकी (Gaddki) 𑚌𑚛𑚮𑚣𑚭𑚥𑚯, गदियाली (Gaddiyali) 𑚡𑚤𑚢𑚵𑚪𑚯, भरमौड़ी (Bharmauri)"},
            {"Gagauz", "Gagauz dili [ɡaɡaˈuz dili] Gagauzça [ɡaɡaˈuzt͡ʃa]"},
            {"Galician", "galego [ɡaˈleɣʊ]"},
            {"Gallo", "galo"},
            {"Galo", "`Galoo"},
            {"Galoli", "Galoli"},
            {"Gamilaraay", "Gamilaraay"},
            {"Ganda", "Oluganda"},
            {"Gandhari", "Gāndhārī"},
            {"Garawa", "Garawa"},
            {"Garhwali", "गढ़वळि (garhwali) [gɜɽʱʋɜliˑ]"},
            {"Garifuna", "Garífuna"},
            {"Garo", "আ'চিক (A·chikku)"},
            {"Gascon", "Gascoun [ɡasˈku(ŋ)]"},
            {"Gaulish", "Gaulish Galáthach hAthevíu (modern Gaulish)"},
            {"Gawar", "Gawar"},
            {"Gawar-Bati", "(gawar bāti) گوَرباتى"},
            {"Gawwada", "Gawwada"},
            {"Gayo", "Basa Gayo"},
            {"Ge'ez", "ግዕዝ (gəʿəz) [ˈɡɨʕɨz] ልሳነ ግዕዝ (lisane gəʿəz)"},
            {"Genoese", "zeneise"},
            {"Georgian", "ქართული ენა (kartuli ena) [kʰartʰuli ɛna]"},
            {"German", "Deutsch [dɔʏtʃ]"},
            {"Ghadamès", "Ɛdimes, Ɣdames"},
            {"Ghomara", "žamaεa, ⵖⵓⵎⴰⵔⴰ"},
            {"Gija", "Gija, Kija"},
            {"Gilaki", "گیلکی (Giləki)"},
            {"Gitxsan", "Gitksanimx̱"},
            {"Godié", "Betɩgwʋʋ [betɪɡʷʊʊ]"},
            {"Godoberi", "ГъибдилӀи мицци (Ɣibdiƛi micci)"},
            {"Goemai", "Goemai"},
            {"Gogo", "Cigogo [ciɡoɡo]"},
            {"Gondi", "Gōndi"},
            {"Gonja", "Ngbanyito"},
            {"Gooniyandi", "Guniandi"},
            {"Goral", "Górolski"},
            {"Gorontalo", "Bahasa Hulontalo"},
            {"Gothic", "𐌲𐌿𐍄𐌹𐍃𐌺𐌰 (Gutiska)"},
            {"Gottscheerish", "Göttscheabarisch"},
            {"Goudu", "Goudu"},
            {"Greek", "ελληνικά (elinika) [eliniˈka]"},
            {"Greenlandic", "Kalaallisut [kalaːɬːisut]"},
            {"Griko", "Γκραίκο (Graíko) Γκρίκο (Griko)"},
            {"Gronings", "Grunnegs Grönnegs"},
            {"Guadeloupean Creole", "Gwadloupéyen"},
            {"Guambiano", "Namrrik, Namtrik"},
            {"Guanano", "Piratapuyo"},
            {"Guanche", "Guanche"},
            {"Guarani", "avañeʼẽ [ʔãʋãɲẽˈʔẽ]"},
            {"Guaymí", "Ngäbere"},
            {"Guere", "Wèè"},
            {"Guernésiais", "Guernésiais [ʤɛɹnɛzie]"},
            {"Gugadja/Kukatja", "Gugadja, Kukatja"},
            {"Guinea-Bissau Creole", "Kriol Kiriol Kriolu Purtuguis"},
            {"Gujarati", "ગુજરાતી (gujarātī) [ɡudʒˈɾɑːtiː]"},
            {"Gurung", "̊तमु क्यी, ཏམུ་ཀི, Tamu Kyi"},
            {"Gusii", "Ekegusii"},
            {"Guugu Yalandji", "Kuku-Yalanji"},
            {"Guugu Yimithirr", "Guugu Yimithirr"},
            {"Gwere", "Lugwere"},
            {"Gwich’in", "Dinjii Zhu’ Ginjik"},
            {"Hadhramautic", "Hadhramautic"},
            {"Haida", "X̱aat Kíl [χatʰ kʰɪl] X̱aadas Kíl  [χatʌs kʰɪl] X̱aayda Kil  [χajtʌ kʰɪl] Xaad kil  [χat kʰɪl]"},
            {"Haisla", "X̄a'’islak̓ala X̌àh̓isl̩ak̓ala"},
            {"Haitian Creole", "Kreyòl ayisyen [kɣejɔl ajisjɛ̃]"},
            {"Hajong", "হাজং (hajông) [ha.dʒɔŋ] হাজং ভাষা (hajông bhasa) [ha.dʒɔŋ bʱasa]"},
            {"Halbi", "हलबी / ହଲବୀ (halbī)"},
            {"Halkomelem", "Halq̓eméylem"},
            {"Hamer(-Banna)", "Hamer(-Banna)"},
            {"Hän", "Häł gołan [hɑɬ koɬan]"},
            {"Hani", "Haqniqdoq"},
            {"Hanuno'o", "Hanunó'o"},
            {"Harari", "ሃራሪ, Gey sinan, حَارَارِ"},
            {"Haroi", "Haroi"},
            {"Haryanvi", "हरियाणवी (hariyāṇawī) [hərijaːɳəwiː] हरयाणवी (harayāṇawī) [hərəjaːɳəwiː]"},
            {"Hatang Kayi", "Hatang Kayi [haˈtaŋ kaˈji]"},
            {"Hausa", "Hausa / هَوْسَ / Halshen Hausa /  هَرْشَن هَوْسَ"},
            {"Hawaiian", "ʻŌlelo Hawaiʻi [ʔoːˈlɛlo həˈvɐjʔi])"},
            {"Hawu", "Lii Hawu [l̺iː havi]"},
            {"Haya", "OluHaya [oluhaja]"},
            {"Hazaragi", "آزرگی"},
            {"Hebrew", "[ʔivˈʁit / ʕivˈɾit] (Ivrit) עברית"},
            {"Heiltsuk", "Haiɫzaqvla"},
            {"Herero", "Otjiherero"},
            {"Hidatsa", "Hiraaciré’"},
            {"Hiligaynon", "Hiniligaynon [hɪlɪˈɡaɪnən] Inilonggo Binisayâ nga Hiligaynon Bisaya nga Ilonggo"},
            {"Himyaritic", "Himyaritic"},
            {"Hindi", "हिन्दी (hindī) [ˈɦɪndiː]"},
            {"Hinukh", "гьинузас мец (hinuzas mec) [hiˈnuzas mɛt͡s]"},
            {"Hiri Motu", "Hiri Motu"},
            {"Hittite", "𒉈𒅆𒇷 (nešili) / nešumnili"},
            {"Hixkaryána", "Hixkaryána"},
            {"Hmar", "Hmar"},
            {"Hmong Dau", "Lus Hmoob Dawb"},
            {"Hmong Njau", "Lug Moob Ntsuab"},
            {"Hmong", "lus Hmoob lug Moob lol Hmongb"},
            {"Hmu", "hveb Hmub"},
            {"Ho", "𑢹𑣉𑣉 𑣎𑣋𑣜 (Ho jagar)"},
            {"Hoava", "Hoava"},
            {"Ho-Chunk / Winnebago", "Hoocąk, Hocąk"},
            {"Hopi", "Hopilàvayi"},
            {"Hsihsia / Tangut", "Tangut"},
            {"Huallaga Quechua", "Wallaqa Runashimi"},
            {"Huambisa", "Wampís"},
            {"Huarijio", "guarijío"},
            {"Huasteco", "Teenek kaaw"},
            {"Huaylla Wanca Quechua", "Wanka Nunashimi Wanuku Runashimi"},
            {"Huichol", "Wixárika Niukiyari"},
            {"Huilliche", "Che Süngun"},
            {"Huli", "Huli [huɭi]"},
            {"Hungarian", "magyar [ˈmɒɟɒr] magyar nyelv [ˈmɒɟɒr ˈɲɛlv]"},
            {"Hunsrik", "Hunsrik"},
            {"Hunzib", "гьонкьос мыц (honƛʼos mɨc) [ˈhont͡ɬʼos mɨt͡s]"},
            {"Hupa", "Na:tinixwe Mixine:whe'"},
            {"Ibaloi", "Inibaloi"},
            {"Iban", "Iban"},
            {"Ibanag", "Ibanag"},
            {"Iberian", "Iberian"},
            {"Ibibio", "Ibibio"},
            {"Icelandic", "íslenska [ˈi:s(t)lɛnska]"},
            {"Ida’an", "Ida’an [idaʔan]"},
            {"Ido", "Ido"},
            {"Idu Mishmi", "Luoba"},
            {"Ifugao", "Ipugaw"},
            {"Igbo", "Ásụ̀sụ̀ Ìgbò"},
            {"Ikizu", "Ikikizu"},
            {"Ikpeng", "Ikeng"},
            {"Ili Turki", "İlı turkeşi"},
            {"Iloko", "Iloko [ikolo] Pagsasao nga Ilokano"},
            {"Inakabnon", "Inabaknon"},
            {"Iñapari", "Iñapari"},
            {"Inari Saami", "Anarâškielâ"},
            {"Indonesian", "Bahasa Indonesia [baˈha.sa in.doˈne.sja]"},
            {"Indus Kohistani", "(Kōstāĩ) كْستٓى"},
            {"Ingrian", "Ižoran keeli"},
            {"Ingush", "гӀалгӀай мотт (ghalghaj mott) [ʁəlʁɑj mot]"},
            {"Innu-aimun (Montagnais)", "Innu-Aimun"},
            {"Inor", "ኢኖር (inor)"},
            {"Interglossa", "Interglossa"},
            {"Interlingua", "Interlingua [inteɾˈliŋɡwa]"},
            {"Interslavic", "меджусловјански, Medžuslovjanski"},
            {"Inuktitut (Eastern Canadian)", "ᐃᓄᒃᑎᑐᑦ (Inuktitut) [inuktiˈtut]"},
            {"Iñupiaq", "Inupiatun"},
            {"Ipai", "'Iipay aa"},
            {"Iquito", "Ikíitu kuwasíini"},
            {"Iraqw", "Kángw Iraqw"},
            {"Iraya", "Iraya"},
            {"Irish", "Gaeilge [ˈɡeːlʲɟə] Gaedhilic/Gaeilic/Gaeilig [ˈɡeːlʲɪc] Gaedhlag [ˈɡeːlˠəɡ]  Gaedhealaing [ˈɡeːl̪ˠɪɲ]  Gaoluinn/Gaelainn [ˈɡeːl̪ˠɪn̠ʲ]"},
            {"Irula", "இருளா (iruḷaa) [ir̪uɭaː]"},
            {"Ishkashimi", "Šëkošmi zëvůk"},
            {"Isnag", "Isnag"},
            {"Istriot", "bumbaro vallese rovignese sissanese fasanese gallesanese"},
            {"Istro-Romanian", "rumârește, vlășește, rumêri-kuvinta"},
            {"Italian", "italiano [itaˈljaːno] lingua italiana [ˈliŋɡwa itaˈljaːna]"},
            {"Itawis", "Itáwit"},
            {"Itbayat", "Itbayaten"},
            {"Itelmen", "итэнмэн (itənmən) [itenmən]"},
            {"Itza’", "Itza’ [itsaɁ]"},
            {"Iu Mien", "Iu Mienh"},
            {"Ivatan", "Chirin nu Ibatan"},
            {"Ivilyuat, Cahuilla", "ʔívil̃uʔat 'Ívillu'at"},
            {"Ixil", "Ixil"},
            {"Iyo'wujwa Chorote", "Yojwaja"},
            {"Jabo", "Jabo"},
            {"Jakaltek", "Jab’xub’al Popti’"},
            {"Jalapa Mazatec", "Ndaxjò"},
            {"Jamaican", "Jimiekn Patwah"},
            {"Jaminjung", "Jaminjung"},
            {"Japanese", "日本語 (nihongo) [ɲihoŋɡo]"},
            {"Japreria", "Japreria"},
            {"Jaqaru", "Jaqaru"},
            {"Jarai", "Jarai"},
            {"Jarawa", "aong"},
            {"Jarud", "ᠵᠠᠷᠤᠳ(jarud) ᠵᠠᠷᠤᠳ ᠠᠮᠠᠨ ᠠᠶᠠᠯᠭᠤ(jarud aman ayalğu)"},
            {"Jatapu", "Jatapu"},
            {"Jaunasari", "जौनसारी, 𑚑𑚵𑚝𑚨𑚭𑚤𑚯 (ğaunasārī) [d͡ʒɔnəsaːriː]"},
            {"Javanese", "Basa Jawa / ꦧꦱꦗꦮ / باسا جاوا [bɔsɔ d͡ʒɔwɔ]"},
            {"Jeju", "제주말(Jeju-mal)"},
            {"Jèrriais(Jersey Norman French)", "Jèrriais"},
            {"Jewish Neo-Aramaic", "אַרָמִית לׅשָנַא"},
            {"Jicarilla", "Abáachi mizaa"},
            {"Jingpho", "ဈိာင်ေဖါစ်(Jìngphòʔ) [tɕiŋ˧˩pʰɔʔ˧˩]"},
            {"Jingulu", "Djingili"},
            {"Jita", "Ecijita"},
            {"Jola-Fonyi", "kujóolay"},
            {"Jru", "Jruq, ຈຼ໌ຣູະ"},
            {"Juǀʼhoan", "Juǀʼhoan"},
            {"Juang", "ଜୁଆଙ୍(juāṅ) [d͡ʑuaːŋ]"},
            {"Judeo-Arabic", "عربية يهودية, ערבית יהודית"},
            {"Judeo-Persian", "(Fārsi) פארסי"},
            {"Juhuri", "çuhuri, жугьури, ז'אוּהאוּראִ"},
            {"Jur Modo", "Jur Modo"},
            {"Jurchen", "(Jushen)"},
            {"Kabardian", "Къэбэрдей-Адыгэбзэ (Qəbərdey-Adıgəbzə) [qabardjaj aːdəɡabza] Къэбэрдейбзэ(qabardejbza)"},
            {"Kabyle", "Taqbaylit"},
            {"Kadazandusun", "Boros Dusun(Central Dusun) Bōs Kadazan(Coastal Kadazan)"},
            {"Kadugli", "Kadugli"},
            {"Kagayanen", "Kagayanen"},
            {"Kaingang", "kanhgág"},
            {"Kaitag", "хайдакьан кув(xaydaq’an kuv) [χɑjdɑqʼɑn kʰuβ]"},
            {"Kaiwá", "Kaiwá"},
            {"Kakabai", "Igora"},
            {"Kala Lagaw Ya", "Kala Lagaw Ya [kala(u) laɡau ja]"},
            {"Kalanguya", "Kalanguya [kɑlɑŋujɑ]"},
            {"Kalderash Romani", "Kaldarári"},
            {"Kalkatungu", "Kalkatungu"},
            {"Kalkoti", "[kʰælkoːʈiː] (khælkōṭī) کھعلکوٹ ى"},
            {"Kalmyk", "ᡍᠠᠯᡅᡏᠠᡎ ᡘᡄᠯᡄᠨ Хальмг келн"},
            {"Kam", "lix Gaeml"},
            {"Kamba", "Kikamba"},
            {"Kambari", "Kambari"},
            {"Kambera", "hilu Humba"},
            {"Kamda", "Tux-mux’dox"},
            {"Kammara", "Kammara"},
            {"Kanakanavu", "Kanakanavu"},
            {"Kanasi", "Sona"},
            {"Kanga", "Kuufo"},
            {"Kangri", "कांगड़ी𑚊𑚭𑚫𑚌𑚪𑚯 (kāṁgaṛī) [kɑ̃ɡəɽi]"},
            {"Kaninuwa", "Wataluma Kaokao"},
            {"Kankanaey", "Kankanaey"},
            {"Kannada", "ಕನ್ನಡ(kannaḍā) [ˈkɐnːɐɖaː]"},
            {"Kannauji", "कन्नौजी(kannaujī) [kənnɔʤi:] देहाती‎(dehātī) [deha: ti:]"},
            {"Kanuri", "Kànùrí"},
            {"Kapampangan", "Kapampangan Amánung Kapampángan Amánung Sísuan"},
            {"Kapingamarangi", "Kirinit"},
            {"Kaqchikel", "Kaqchikel Ch'ab'äl"},
            {"Karaim", "къарай тили, Karay dili(lashon kedar) לשון קדר‎"},
            {"Karakalpak", "Қарақалпақ тили, Qaraqalpaq tili, قاراقالپاق تىلى"},
            {"Karamanli Turkish", "Καραμανλήδικα (Karamanlídika)"},
            {"Karamojong", "ŋaKarimojoŋ"},
            {"Karata", "кӏкӏирлӏи (k’k’irłi) [k’k’irɬ’i]"},
            {"Karbi", "কাৰ্বি(karbi)"},
            {"Karelian", "karjal kariela karjala"},
            {"Karen(Eastern Pwo)", "ဖၠုံ(phlou) [pʰlo] ဖၠုံယှိုဝ်(phlou youw)"},
            {"Karuk", "araráhih"},
            {"Kasem", "Kasena"},
            {"Kashaya", "Kʼahšá:ya"},
            {"Kashibo", "Cacataibo"},
            {"Kashinawa", "Hantxa Kuin Huni Kui"},
            {"Kashmiri", "कॉशुर, 𑆑𑆳𑆯𑆶𑆫𑇀, كٲشُر (koshur) [kəːʃur]"},
            {"Kashubian", "kaszëbsczi kaszëbsczi jãzëk"},
            {"Kaska", "Dene Zágéʼ"},
            {"Kaurna", "Kaurna"},
            {"Kavalan", "Kbalan"},
            {"Kawaiisu", "Nüwü'abigidü"},
            {"Kawésqar", "Kawésqar Afséksta"},
            {"Kayah / Red Karen / Karenni", "ကယား, ꤊꤢꤛꤢꤟ(kayah)"},
            {"Kazakh", "Қазақ тілі(qazaq tili) [qɑˈzɑq tɪˈlɪ] қазақша(qazaqsha) [qɑzɑqˈɕɑ], قازاقشا‎ / قازاق تىلى‎"},
            {"Keiga", "Sani ma-yɛgaŋ"},
            {"Kekchi / Q'eqchi'", "Q'eqchi'"},
            {"Kelabit", "karuh Kelabit karuh tauh"},
            {"Keliko", "Kaliko"},
            {"Kera", "kéérá"},
            {"Keres", "Keres"},
            {"Kerinci", "Baso Kincai"},
            {"Ket", "Остыганна ӄа’ (Ostyganna qa')"},
            {"Khakas", "Хакас тілі(Khakas tîlî)"},
            {"Khalaj", "Khalaj, (Xələc dili) خلج دێلێ"},
            {"Khaling", "खालिङ (khāliṅ) [kʰaːliŋ] ख्या:ल् ब्रा: (khel brā)[kʰɛ̂l brâː]"},
            {"Kham(Eastern Parbate)", "खाम भाषा(khām bhāṣā) [kʰɐm bɐsɐ]"},
            {"Khamnigan Mongol", "ᠬᠠᠮᠨᠢᠭᠠᠨ  (Xamniğan) [qamniɣan]"},
            {"Khams Tibetan", "ཁམས་སྐད(khamké)"},
            {"Khamti", "ၵံးတီႈ(khamtī) လိꩱ့်တဲးၵမ်းတီႈ(written) ၵၢမ်းတဲးၵံးတီႈ(spoken)"},
            {"Khandeshi", "खान्देशी(khāndeśī) [kʰandeʃi:]"},
            {"Khanty", "Ханты(Xanty)"},
            {"Kharia", "खड़िया(khaṛiyā) [kʱaɽija:]"},
            {"Khasi", "Ka Ktien Khasi, ক ক্ত্যেন খসি [ka kt̪eːn kʰasi]"},
            {"Khinalug", "каьтш мицI, kätš micʼ"},
            {"Khitan", "𘱿𘱤 (khitan)"},
            {"Khmer", "ភាសាខ្មែរ(phéasa khmê) [pʰiəˈsaː kʰmae],"},
            {"Khmu", "ກຶມຫມຸ‎(kamhmu)"},
            {"Khoekhoe", "Khoekhoegowab"},
            {"Khorasani Turkic", "Xorasan Türkçesi, خراسان تركچىسى"},
            {"Khorchin(Mongolian)", "ᠬᠣᠷᠴᠢᠨ(qorčin) [ˈxɔrʧɪn] ᠬᠣᠷᠴᠢᠨ ᠠᠮᠠᠨ ᠠᠶᠠᠯᠭᠤ(qorčin aman ayalγu)"},
            {"Khortha", "खोरठा(khīrṭhā) [kʰiːrʈʰaː]"},
            {"Khowar", "(khowar) کهووار"},
            {"Khufi", "Xuf ziv"},
            {"Khwarshi", "акьилхъо (atł’ilqo) [at͡ɬ’ilqo]"},
            {"Ki'che'", "Qatzijob'al"},
            {"Kichwa", "Kichwa simi"},
            {"Kickapoo", "Kikapú"},
            {"Kiga / Chiga", "Orukiga RuChiga RuKiga"},
            {"Kikai", "シマユミタ (simayumita) [simajumita]"},
            {"Kikuyu", "Gĩkũyũ [ɣēkōjó]"},
            {"Kildin Sámi", "кӣллт са̄мь кӣлл(kiillt saam' kiill)"},
            {"Kiliwa", " Koléew Ñaja'"},
            {"Kimbundu", " Kimbundu"},
            {"Kinabalian", " Kinabalian"},
            {"Kinaray-a", " Kinaray - a"},
            {"Kinyarwanda", " Ikinyarwanda"},
            {"Kiribati", " Taetae ni Kiribati"},
            {"Kirundi", " íkiRǔndi"},
            {"Kisi", " Kikisi"},
            {"Kissi", " Kissi"},
            {"Kituba", " Munukutuba"},
            {"Klallam", " Nəxʷsƛʼayʼəmúcən"},
            {"Klamath-Modoc", " maqlaqsyals"},
            {"Klata", " Bagobo - Klata"},
            {"Knaanic", " (Lešon kenaan) לשון כנען"},
            {"Koasati", "Kowassaati"},
            {"Kodava", "ಕೊಡವ ತಕ್ಕು(kodava takk)"},
            {"Kodeoha", "Kodeoha"},
            {"Koho", "Kơho"},
            {"Kokborok", "Kókborok / ককবরক"},
            {"Kolam", "Kolam"},
            {"Kom(Cameroon)", "Itaŋikom"},
            {"Kom(India)", "Kom Rem"},
            {"Komering", "Cawa Komering / كومريڠ"},
            {"Komi", "Коми кыв(Komi kyv)"},
            {"Komo", "Go-kwom, Tta Komo"},
            {"Konda-Dora", "Konda-Dora"},
            {"Kongo", "Kikongo"},
            {"Konjo", "Olukonjo"},
            {"Konkani", "कोंकणी, ಕೊಂಕಣಿ, കൊങ്കണി, كونكڼى(konknni) [kõkɳi]"},
            {"Korean", "한국어[韓國語] (hanguk-eo) [ha(ː)n.ɡu.ɡʌ] - South Korea  조선말[朝鮮말] (chosŏn-mal) [tso.sɔn.mal] - North Korea"},
            {"Korku", "कोरकू(korkū) [korku:]"},
            {"Koryak", "нымылан(nymylan)"},
            {"Kosraean", "Kosrae"},
            {"Koti", "Ekoti"},
            {"Kotia", "Kotia"},
            {"Kove", "Kove"},
            {"Koya", "Koya"},
            {"Koyukon", "Denaakk'e"},
            {"Kpelle", "Kpɛlɛwoo"},
            {"Kri", "meengq Kri"},
            {"Krongo", "Krongo"},
            {"Krymchak", "‍кърымчах тыльы(qrımçah tılyı)"},
            {"Kryts", "Кърыцӏаь мез, Ġryc’ä mez"},
            {"Kubachi", "гӀугъбуган (ghug’bugan)"},
            {"Kufa", "Kuufo"},
            {"Kuku Nyungkal", "Kuku Nyungkal Gugu Njunggal"},
            {"Kulisusu", "Pogau Kolinsusu"},
            {"Kullui / Kulvi", "𑚊𑚰𑚥𑚷𑚱𑚃 / कुळूई (kuḷūī) [kuɭuːiː] 𑚊𑚰𑚥𑚷𑚱𑚦𑚯 / कुल्वी (kulvī) [kulwiː]"},
            {"Kumandy", "куманды (kumandı) [kumandɯ]"},
            {"Kumaoni", "कुमाऊँनी (kumaaũũnii)"},
            {"Kumeyaay", "K’miai"},
            {"Kumyk", "Къумукъ тил / qumuq til / قموق تيل"},
            {"Kumzari", "(Lāǧa kumzārī) لاغة كمزار"},
            {"Kuna", "Dulegaya"},
            {"Kunjen", "Gunjen"},
            {"Kuot", "Panaris"},
            {"Kupia", "Kupia"},
            {"Kurdish", "(Kurdî) کوردی (Kurmancî) کورمانجی (Sorani)  سۆرانی "},
            {"Kuria", "Igikuria"},
            {"Kurmali", "কুড়মালি (kuṛamāli) কুর্মালী (kurmālī) कुड़मालि (kuṛamāli) କୁଡ଼ମାଲି (kuṛamāli)"},
            {"Kurti", "Ndrukul"},
            {"Kurukh", "कुड़ुख़, কুড়ুখ, କୁଡ଼ୁଖ (kuṛukh) [kuɽukʰ]"},
            {"Kusaal", "Kʋsaal"},
            {"Kusunda / Mihaq", "मिहाक (mihāk) [miɦjɑːk] कुसान्डा (kusānda) [kusanda]"},
            {"Kutchi", "કચ્છી (kacchī) [ˈkɐtʃtʃʰiˑ] ڪڇّي"},
            {"Kutenai", "Kutenai"},
            {"Kuuk Thaayorre", "Kuuk Thaayorre"},
            {"Kuy", "กูย, កួយ, ກູຢ (kūy) [kuːj]"},
            {"Kven", "kvääni kainu kväänin kieli kainun kieli"},
            {"Kwak̓wala", "Kwak̓wala"},
            {"Kyrgyz", "Кыргыз тили (Kyrgyz tili) [qɯɾʁɯz tili] قىرعىز تىلى"},
            {"Láá Láá Bwamu", "làa làa bũamu"},
            {"Laalaa", "Léhar"},
            {"Lacandon", "Jach-t’aan [xatʃ tʼaːn]"},
            {"Ladakhi", "ལ་དྭགས་སྐད་ (lədəks siskət)"},
            {"Ladin", "ladin  [la'din]) lingaz ladin  [liŋ'gat͡s la'din]"},
            {"Ladino", "djudeo-espanyol, жудеоеспањол, ג'ודיאו-איספאנייול"},
            {"Lahu", "Ladhof [lɑ˥˧xo˩]"},
            {"Lak", "Лакку маз (Lakku maz)"},
            {"Lakota (Sioux)", "Lakȟótiyapi [la.ˈkxo.ti.ja.pi]"},
            {"Lambadi", "बंजारा (baṁjārā) లంబాడి (laṁbāḍi) ಲಂಬಾಣಿ (laṁbāṇi)"},
            {"Lambya", "Ichilambya ChiLambya"},
            {"Lampung", "cawa Lampung"},
            {"Lango / Leb Lango", "Lëblaŋo"},
            {"Lanna / Northern Thai", "Kam Mueang, คำเมือง"},
            {"Lao", "ລາວ (lao) [láːw]  ພາສາລາວ (phasa lao) [pʰáːsǎːláːw] "},
            {"Latgalian", "latgalīšu volūda"},
            {"Latin", "Lingua Latina"},
            {"Latino sine Flexione", "Latino sine Flexione"},
            {"Latvian", "latviešu valoda [latviɛʃu valuɔda]"},
            {"Laz", "ლაზური ნენა (Lazuri nena)"},
            {"Ledo Kaili", "Palu"},
            {"Lele", "Lele"},
            {"Lepcha", "Róng-Ríng"},
            {"Lepontic", "Leptonic"},
            {"Lezgi", "лезги, лезги чӀал"},
            {"Lhomi", "ल्होमी‎ (lhomī)"},
            {"Lhowa", "ॱलोवा (lhowā)"},
            {"Ligurian", "Lìgure"},
            {"Lillooet", "St’át’imcets, Lil'wat7úlmec"},
            {"Limba", "Hulimba"},
            {"Limbu", "ᤕᤠᤰᤌᤢᤱ ᤐᤠᤴ (yakthung pān)"},
            {"Limburgish", "Limburgs"},
            {"Lingala", "Lingala"},
            {"Lingua Franca Nova", "Lingua Franca Nova  [ˈliŋɡwa ˈfraŋka ˈnɔva]"},
            {"Lipan Apache", "Hleh-pai Ndé, Lépai-Ndé"},
            {"Lipo", "𖼖𖽡𖾑 𖼀𖽑𖽙 (lipho) [li˥pʰo˩˨]"},
            {"Liq’wala", "Liq̓ʷala [liqʷ’ala]"},
            {"Lisu", "ꓡꓲ-ꓢꓴ [lisu]"},
            {"Lithuanian", "lietuvių kalba [lʲɪɛtʊvɪuː kɐɫbɐ]"},
            {"Livonian", "Līvõ kēļ"},
            {"Livvi-Karelian", "livvin kieli"},
            {"Llanito", "Llanito"},
            {"Lojban", "la .lojban. [laʔˈloʒbanʔ]"},
            {"Lokoya", "Lokoya"},
            {"Loma", "Löömàgòòi [lɔːmàɡòːi] Löghömàgòòi [lɔɣɔmàɡòːi]"},
            {"Lombard", "Lombard, Lumbaart"},
            {"Lopit", "Lopit"},
            {"Lorain", "Lorin"},
            {"Lote", "Lote [lɔte]"},
            {"Lotuko", "Otuho"},
            {"Loup", "Niipmok"},
            {"Lovari", "Lovara Romani"},
            {"Low German", "Plattdüütsch Nedderdüütsch"},
            {"Lozi", "siLozi"},
            {"Luchazi", "ChiLuchazi"},
            {"Ludic", "l’üüd’ikš, l’üüd’ikiel’"},
            {"Luganda", "Oluganda"},
            {"Lugbara", "Lugbara"},
            {"Luiseño", "Cham'teela"},
            {"Lule Sámi", "julevsámegiella"},
            {"Lumun", "Lumun"},
            {"Lun Bawang / Lun Dayeh", "Buri’ Lun Bawang Buri’ tau"},
            {"Luobohe Miao", "Ā-hmiò"},
            {"Luri", "[lo̝riː] (lorī) لوری"},
            {"Lushootseed", "dxʷləšúcid"},
            {"Lusitanian", "Lusitanian"},
            {"Luvale", "Chiluvale"},
            {"Luwian", "Luwian"},
            {"Luxembourgish", "Lëtzebuergesch [ˈlətsəbuəjəʃ] "},
            {"Lycian", "𐊗𐊕𐊐𐊎𐊆𐊍𐊆 (trm̃mili)"},
            {"Lydian", "(sfardẽtiš) 𐤮𐤱𐤠𐤭𐤣𐤶𐤯𐤦𐤳"},
            {"Maasai", "ɔl Maa"},
            {"Macedonian", "македонски (makedonski jazik), [maˈkɛdɔnski ˈjazik] македонски (makedonski)"},
            {"Machiguenga", "Matsigenka"},
            {"Macushi", "Macushi"},
            {"Ma'di", "Ma'diti"},
            {"Madurese", "Bhâsa Madhurâ / ꦧꦱꦴꦩꦝꦸꦫꦴ / بَهاسَ مَدورا"},
            {"Magahi", "मगही (magahī)"},
            {"Magar", "मगर ढुट‎ (magar ḍhuṭ)"},
            {"Maguindanao", "Magindanawn"},
            {"Mahasu Pahari", "महासुई (mahāsui) [məɦaːsui] महासुई क्योंथली (mahāsui kyoṁthalī) [məɦaːsui kjoŋt̪ʱəː]"},
            {"Maithili", "Macushi"},
            {"Makah", "qʷi·qʷi·diččaq"},
            {"Makasarese", "ᨅᨔ ᨆᨀᨔᨑ, Basa Mangkasara'"},
            {"Makhuwa", "Makhuwa"},
            {"Makonde", "Chi(ni)makonde"},
            {"Makurap", "Makurap"},
            {"Malagasy", "malagasy [ˌmalaˈɡasʲ] fiteny malagasy"},
            {"Malay (Terangganu)", "Base Tranung [bahsɘ tɣanuŋ] Bahse Tranung Base Tghanung Bahse Tghanung Cakak Tranung [tʃakaʔ tɣanuŋ]"},
            {"Malay", "Bahasa Melayu, بهاس ملايو"},
            {"Malayalam", "മലയാളം (malayāḷam) [mʌlʌjaːɭʌm]"},
            {"Maldivian", "[d̪iˈʋehi] (dhivehi) ދިވެހި"},
            {"Malecite-Passamaquoddy", "Malecite-Passamaquoddy"},
            {"Mali", "Mali"},
            {"Maltese", "Malti [mɐlti̞:]"},
            {"Malto", "পাহাড়িয়া (pāhāṛiyā) पहाड़िया (pahāṛiyā) Paháṛiyá"},
            {"Mam", "Qyol Mam"},
            {"Mamaindê", "Mamainsahai’gidu"},
            {"Mamanwa", "Minamanwa"},
            {"Mampruli", "Ŋmampulli Ŋmampurili"},
            {"Manado Malay", "Bahasa Manado"},
            {"Manchu", "ᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ, manju gisun"},
            {"Mandaic", "Mandāyì Raṭnā  ࡓࡀࡈࡍࡀ‎"},
            {"Mandan", "Nų́ų́ʔetaa íroo"},
            {"Mandar", "Mandar"},
            {"Mandari", "Kútúk nà mùndárì"},
            {"Mandeali", "मंडयाल़ी, 𑚢𑚘𑚶𑚖𑚮𑚣𑚭𑚥𑚯 (maṇḍayālī)"},
            {"Mandinka", "Mandingo, لغة مندنكا"},
            {"Mangareva", "Te Reo Magareva [te reo maŋareva]"},
            {"Manggarainese", "Manggarai"},
            {"Manide", "Manide"},
            {"Maninka", "Maninkakan"},
            {"Manipuri", "Meiteilon, ꯃꯤꯇꯩꯂꯣꯟ"},
            {"Mankanya", "Uhula"},
            {"Mano", "Mano"},
            {"Mansi", "ма̄ньси ла̄тыӈ (mān'si lātiŋ)"},
            {"Manumanaw Karen", "Manumanaw"},
            {"Manx", "Gaelg [ɡɪlk/ɡɪlɡ]"},
            {"Maore", "Shimaore"},
            {"Māori", "Māori [ˈmaːɔɾi] te reo Māori [tɛ ˈɾɛ.ɔ maːɔɾi] te reo [tɛ ˈɾɛ.ɔ]"},
            {"Mapuche", "Mapudungun"},
            {"Maranao", "Mëranaw"},
            {"Marathi", "मराठी (Marāṭhī) [məˈɾaʈʰi], 𑘦𑘨𑘰𑘙𑘲"},
            {"Marba", "Azumeina"},
            {"Mari (Hill / Western)", "Кырык мары йӹлмӹ (Kyryk mary jÿlmÿ) [kɨrɨk marɨ jəlmə] Мары йӹлмӹ (Mary jÿlmÿ) [marɨ jəlmə]"},
            {"Mari (Meadow / Eastern)", "олык марий (olək marij) [olək marij]"},
            {"Mari (Northwestern)", "Йөтнӫмӓл-кӓсвел маре йӹлмӹ (Jůtnẙmäl-käsvel mare jÿlmÿ) [jůtnẙmæl kæsvɛl marɛ jylmy]"},
            {"Maricopa", "Piipaash chuukwer Xalychidoma chuukwer"},
            {"Marma", "ရခိုင်ဘာသာ (rahkuing bhasa) [ɹəkʰàɪɴbàθà]"},
            {"Marquesan (North)", "Te èo ènana"},
            {"Marquesan (South)", "Te èo ènata"},
            {"Marshallese", "Kajin M̧ajeļ Kajin Majōl [kɑzʲinʲ(i)mˠɑːzʲɛlˠ]"},
            {"Martu Wangka", "Wangkatjunga"},
            {"Marwari", "मारवाड़ी, 𑅬𑅐𑅭𑅯𑅐𑅲𑅑 (mārvāṛī) [mɑɾvɑɽi] مارواڑى"},
            {"Masaaba", "Masaaba Lumasaaba"},
            {"Masbateño", "Minasbate"},
            {"Mashan Miao", "Hmangp"},
            {"Maskelynes", "Kuliviu"},
            {"Massachusett", "Wôpanâôtuwâôk [wãpanaːãˈtuwaːãk] Muhsachuweesee unôtuwâôk  [məhsatʃəw[iː]sət ənãtuwaːãk] Massachusee unnontꝏwaonk"},
            {"Matigsalug", "Matig-Salug Manobo"},
            {"Mato", "Mato"},
            {"Maung", "Gun-Marung"},
            {"Mauritian Creole", "Kreol Morisien [kʁeol moʁisjɛ̃ / moʁiʃɛ̃]"},
            {"Mayo", "Yoreme Nokki"},
            {"Mazahua", "Jñatjo"},
            {"Mazandarani", "مازرونی (Mazandarani) "},
            {"Mazatec", "En Ngixo"},
            {"Mbula", "Mbula"},
            {"Mbum", "Mbum"},
            {"Mbunda", "Chimbúùnda"},
            {"Meänkieli", "meänkieli [meænkieli]"},
            {"Megleno-Romanian", "vlășéște limba vlășească"},
            {"Melanau", "Melanau [mɛlanau]"},
            {"Mele-Fila", "Ifira-Mele"},
            {"Mende", "Mɛnde yia"},
            {"Ménik", "Ménik [menik]"},
            {"Menominee", "omǣqnomenēweqnæsewen"},
            {"Mentawai", "Behase Mentawei"},
            {"Meriam Mir", "Meriam Mir"},
            {"Meroïtic", "Meroïtic"},
            {"Mescalero-Chiricahua", "Ndee bizaa"},
            {"Mewari", "मेवाड़ी (mewāṛī) [mewaːɽiː]"},
            {"Miami", "Myaamia"},
            {"Michif", "Michif"},
            {"Migaama", "Migaama [mìgáàmá]"},
            {"Miju", "Kùmán"},
            {"Mikasuki", "Mikasuki"},
            {"Mi'kmaq", "Míkmawísimk"},
            {"Minangkabau", "Baso Minang(kabau)"},
            {"Mingrelian", "მარგალური ნინა (margaluri nina)"},
            {"Mirandese", "lhéngua mirandesa"},
            {"Miriwoong", "Miriwoong"},
            {"Misantla Totonac", "Laakanaachiwíin"},
            {"Miskito", "Mískitu"},
            {"Mixtec", "Tu'un Sávi Dà'àn Dávi"},
            {"Miya", "vә́na mίy"},
            {"Miyakoan", "ミャークフツ (myākufutsu) [mjaːkufutss̩]"},
            {"Mizo", "Mizo ṭawng"},
            {"Mòcheno", "Bersntolerisch"},
            {"Mocho’", "qatô:k"},
            {"Mogholi", "مُغُلی (mogholi)"},
            {"Mohawk", "Kanienʼkéha [ɡa.njʌ̃ʔ.ˈɡe.ha]"},
            {"Mohegan", "Mohegan"},
            {"Mohican", "Mahiikan Maʔeekuneeweexthowãakun"},
            {"Mojave", "Hamakhav"},
            {"Mokilese", "Mwoakilloa"},
            {"Moksha", "мокшень кяль (mokšenj kälj) [ˡmɔkʃenʲ kælʲ]"},
            {"Molbog", "limba moldovenească (лимба молдовеняскэ)"},
            {"Molbog", "Molbog"},
            {"Moloko", "Ma Məloko Məloko  [mʊlɔkʷɔ]"},
            {"Mon", "ဘာသာ မန် (bhāsā mon) [pʰesa mɔn]"},
            {"Monégasque", "Munegascu"},
            {"Mongolian", "ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ монгол ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ монгол хэл [ˈmɔɴɢɔ̆ɮ çiɮ]"},
            {"Mongondow", "Bolaang Mongondow"},
            {"Monguor", "Monguor"},
            {"Mono", "Mono"},
            {"Montenegrin", "Crnogorski jezik, Црногорски језик"},
            {"Mopan", "Maya Mopán"},
            {"Mori Atas", "Mori Atas"},
            {"Mori Bawah", "Mori Bawah"},
            {"Moriori", "Te Rē Mōriori"},
            {"Morokodo", "Morokodo"},
            {"Moronene", "Moronene"},
            {"Mortlockese", "kapsen Mwoshulók"},
            {"Moru", "Kala Moru"},
            {"Mossi", "Mòoré"},
            {"Motu", "Motu"},
            {"Mozarabic", "Latín, לטן, لتن‎"},
            {"Mro", "Mru"},
            {"Mualang", "Basa Mualang"},
            {"Mukha Dora", "Mukha Dora"},
            {"Muna", "Muna"},
            {"Mundang", "zah Mundaŋ"},
            {"Mundari", "মুণ্ডরি, मुण्डरि, ମୁଣ୍ଡରି, Muṇḍari"},
            {"Munji", "مونجى (munji)"},
            {"Munsee", "Huluníixsuwaakan"},
            {"Muong", "Thiểng Mường, 㗂𤞽"},
            {"Murrinh-Patha", "Murrinh-Patha"},
            {"Murui Huitoto", "Murui Huitoto"},
            {"Musey", "Museyna"},
            {"Musi", "Baso Palembang"},
            {"Mutsun", "Mutsun"},
            {"Mwaghavul", "Mwaghavul"},
            {"Mwangwego", "Mwangwego"},
            {"Mwani", "Kimwani"},
            {"Mwotlap", "Mwotlap"},
            {"Nǁng", "Nǁng"},
            {"Nabataean", "Nabataean"},
            {"Nagamese Creole", "Nagamiz"},
            {"Nahuatl", "Nāhuatl [ˈnaːwatɬ] Nāhuatlahtōlli [naːwat͡laʔˈtoːlli] Mēxihcatlahtōlli Mācēhuallahtōlli Mēxihcacopa [meːʃiʔkaˈkopa] "},
            {"Nama", "Khoekhoegowab"},
            {"Nambikwara", "Kitãulhu"},
            {"Nanai", "Нанай (Nanaj) Нанайэ (Nanaje)"},
            {"Nancowry", "मुओत (mūöt)"},
            {"Nande", "Kinande"},
            {"Nanti", "Pucapucari"},
            {"Narim", "Boya"},
            {"Naro", "Nharo"},
            {"Narragansett", "Nãikanset"},
            {"Naskapi", "ᓇᔅᑲᐱ (naskapi) ᐃᔪᐤ ᐃᔨᒧᐅᓐ (iyuw iyimuun)"},
            {"Natchez", "Naacee"},
            {"Nauruan", "Dorerin Naoero Ekaiairũ Naoero"},
            {"Navajo", "Diné Bizaad [tìnépìz̥ɑ̀ːt] Naabeehó bizaad [nɑ̀ːpèːhópìz̥ɑ̀ːt]"},
            {"Naviclé", "Guisnai"},
            {"Naxi", "Naqxi [nɑ˥˥ ɕi˧˧] Naqxi geezheeq"},
            {"Ndebele (Northern - South Africa)", "SiNdebele sa seNyakatho"},
            {"Ndebele (Northern - Zimbabwe)", "isiNdebele isiNdebele saseNyakatho"},
            {"Ndebele (Southern)", "isiNdebele isiNdebele seSewula"},
            {"Ndrumbea", "Ṇã́ã Ṇḍùmbea"},
            {"Ndyuka / Aukan", "Okanisi, Ndyuka tongo"},
            {"Neapolitan", "napulitano"},
            {"Negidal", "Неғида хэсэнин (Neǧida hesenin)"},
            {"Nenets", "Ненэця’ вада (Nenėcjaˀ vada)"},
            {"Neo-Mandaic", "Mandāyî"},
            {"Nepali", "नेपाली (nepālī) [ˈnepali]"},
            {"Newar (Nepal Bhasa)", "नेपाल भाषा (Newah Bhaye)"},
            {"Neyo", "Newole [nɪwɔlɪ]"},
            {"Nez Perce", "Nimipuutímt"},
            {"Ngaanyatjarra", "Ngaanyatjarra"},
            {"Ngaju", "Ngaju [ŋaɟu]"},
            {"Nganasan", "ня” (njaʔ) [nʲɐʔ]"},
            {"Ngiyambaa", "Ngiyambaa"},
            {"Ngizim", "miya Ngǝzǝm"},
            {"Nhangu", "Yan-nhaŋu [jan n̻aŋu]"},
            {"Nheengatu", "ñe'engatú [ɲɛʔɛ̃ŋaˈtu]"},
            {"Nias", "Li Niha"},
            {"Nihali", "Nihali"},
            {"Nimadi", "निमाडी (nimāḍī) [nimaɖiː]"},
            {"Nisga’a", "Nisg̱a’a"},
            {"Niuafoʻou", "Niuafoʻou ko te lea faka Niuafoʻou"},
            {"Niuean", "Vagahau Niuē"},
            {"Nivaclé", "Guisnai"},
            {"Nivkh / Gilyak", "Нивхгу диф (Nivxgu dif) [ɲivxɡu dif]"},
            {"Nkore", "Runyankore"},
            {"Nobiin", "Nòbíín"},
            {"Nogai", "Ногай тили (Noğay tili)  Ногайша (Noğayşa)"},
            {"Nomatsiguenga", "inato"},
            {"Noon", "Noon"},
            {"Noongar", "Nyungaa-wangka"},
            {"Norfuk", "Norfuk"},
            {"Norn", "Norroena"},
            {"Northern Khmer", "พาซาคแมรซุริน / ភាសាខ្មែរសុរិន្ទ្រ [psaː kʰmɛːr]"},
            {"Northern Paiute", "Numu Paviotso"},
            {"Northern Pomo", "Northern Pomo"},
            {"Northern Pwo (Karen)", "พลอง (phlong)"},
            {"Northern Qiang", "Rrmearr, & leHS [ʐmeʐ]"},
            {"Northern Sámi", "davvisámegiella"},
            {"Northern Sotho", "Sesotho sa Leboa Sepedi"},
            {"Northern Thai (Kam Mueang)", "Kam Mu'ang"},
            {"Norwegian", "norsk [ˈnɔʂk / ˈnɔʁsk]"},
            {"Novial", "Novial"},
            {"Nso / Lamnso", "Lamnsɔ’"},
            {"Nubi", "كينوبي (Ki-Nubi)"},
            {"Nuer", "Thok Naath"},
            {"Nukuoro", "Nunggubuyu "},
            {"Nukuria", "Nukuria"},
            {"Nunggubuyu", "Wubuy"},
            {"Nupe / Nupe-Nupe-Tako", "Nupe"},
            {"Nushu", "(njiu21 xiu33) 𛆁 [nỳʂú] 𛈬"},
            {"Nusu", "Nusu"},
            {"Nuu-Chah-Nulth (Nootka)", "Nuučaan̓uł T'aat'aaqsapa"},
            {"Nuxalk", "ItNuxalkmc"},
            {"Nyah Kur", "ญัฮกุ้ร‎ (nyah kur) เนียะกวล‎ (niakuol)"},
            {"Nyakyusa", "Kɨnyakyʉsa"},
            {"Nyamwezi", "Kinyamwezi"},
            {"Nyelâyu", "Nyelâyu"},
            {"Nyemba", "Nyemba [ɲeᵐba]"},
            {"Nyole", "Lunyole"},
            {"Nyungwe", "Cinyungwe"},
            {"Nzema", "Nzema"},
            {"Obo", "Manobo"},
            {"Obolo", "Obolo"},
            {"Occidental", "Occidental"},
            {"Occitan (Auvergnat)", "auvernhat"},
            {"Occitan (Languedocien)", "lengadocian [leŋɡoðuˈsja]"},
            {"Occitan (Limousin)", "lemosin"},
            {"Occitan (Provençal)", "pro(u)vençau [pʀuvenˈsaw]"},
            {"Occitan", "Occitan"},
            {"Odia / Oriya", "ଓଡ଼ିଆ (oṛiā) [oˈɽiaː]"},
            {"Ojibwe", "Anishinaabemowin, ᐊᓂᔑᓈᐯᒧᐎᓐ"},
            {"Oji-Cree", "Anishininiimowin, ᐊᓂᔑᓂᓂᒧᐏᐣ"},
            {"Okanagan", "n̓səl̓xcin̓"},
            {"Okinawan", "沖縄口, ウチナーグチ, Uchinaaguchi"},
            {"Okinoerabu", "島ムニ (shimamuni) [ʃimamuni]"},
            {"Old Church Slavonic", "ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ ⰧⰈⰟⰊⰍⰟ словѣ́ньскъ ѩꙁꙑ́къ slověnĭskŭ językŭ"},
            {"Old English / Anglo-Saxon", "Ænglisc"},
            {"Old Norse", "Dǫnsk tunga Norrœnt mál"},
            {"Old Nubian", "Ⲛⲟⲩⲃⲓⲛ"},
            {"Old Turkic / Orkhon", "Orkhon"},
            {"Olu'bo", "Lolubo"},
            {"Oluta Popoluca", "Yaak'awü"},
            {"Omaha", "Umoⁿhoⁿ"},
            {"Ona", "Selk'nam"},
            {"Oneida", "Onʌyotaʼa:ka"},
            {"Onge", "Öñge"},
            {"Onondaga", "Onǫdaʼgegáʼ Onoñdaʼgegáʼ Onoñdaʼgegáʼ nigaweñoʼdeñʼ [onũdaʔɡeɡáʔ niɡawẽnoʔdẽʔ]"},
            {"Ontong Java", "Luangiua"},
            {"O'odham", "Oʼodham ha-ñeʼokĭ Oʼottham ha-neoki [ˈʔɔʔɔɖam haɲɨɁɔki] Oʼodham ñiok [ˈʔɔʔɔɖam ɲɨɔk]"},
            {"Oowekyala", "’Uik̓ala"},
            {"Ormuri", "(ormūṛī) اورموړی"},
            {"Oroch", "Орочи кэсэни (Oroči keseni) [ɔrɔʧi kəsəni]"},
            {"Orok", "уйльта (ujlta), ульта (ulta)"},
            {"Oromo", "Afaan Oromoo [ʌfɑːn ɔrɔmoː] Oromiff"},
            {"Oroqen", "Oroqen"},
            {"Oroshor", "Rōšōrvī ziv"},
            {"Osage", "Wazhazhe ie"},
            {"Oscan", "(FANGVAM OSCA) 𐌀𐌊𐌔𐌏 𐌌𐌀𐌖𐌂𐌍𐌀𐌚"},
            {"Oshiwambo", "Oshiwambo"},
            {"Ossetian", "ирон ӕвзаг (iron ævzag) [iˈɾon ɐvˈzaɡ] дигорон ӕвзаг (digoron ævzag) [digoˈɾon ɐvˈzaɡ]"},
            {"Otomi", "Hñähñu"},
            {"Ottawa", "Nishnaabemwin Daawaamwin"},
            {"Paakantyi", "Paakantyi"},
            {"Paama", "Paama"},
            {"Páez", "Nasa Yuwe"},
            {"Pahari", "पहरी (paharī) [pahariː]"},
            {"Paicî", "Paicî"},
            {"Paipai", "Akwa'ala"},
            {"Paite", "Paite"},
            {"Paiwan", "Pinayuanan"},
            {"Palauan", "a tekoi er a Belau"},
            {"Palaung", "Palaung"},
            {"Palawano", "Palaw’an"},
            {"Palenquero", "Lengua"},
            {"Pali", "पालि (Pāli)"},
            {"Palikúr", "Pa'ikwené Pa'ikwaki"},
            {"Palula", "پالولہ [pəʂt̪oˈ, pʊxt̪oˈ, pəʃt̪oˈ, pəçt̪oˈ] Pax̌tó"},
            {"Panare", "E’ñapa"},
            {"Pangasinan", "Salitan Pangasinan"},
            {"Pangwali", "पंगवाड़ी, 𑚞𑚫𑚌𑚦𑚭𑚪𑚯 (pãgawāṛī) [pɑŋwɑːɽiː]"},
            {"Pa'O", "ပအိုဝ်ႏ (paʼṓ) ပအိုဝ်ႏဘာႏသာႏ (paʼṓ w-bhā́sā́)"},
            {"Papantla Totonac", "Tutunakú"},
            {"Papiamento", "Papiamentu"},
            {"Paraujuano", "Añú"},
            {"Paresi", "Haliti"},
            {"Parji, Porja", "Parji, Porja"},
            {"Parkari Koli", "پارڪرِي‎"},
            {"Parthian / Arsacid Pahlavi", "Pahlawānīg"},
            {"Pashto", "Pəx̌tó [pəʂˈt̪o, pʊxˈt̪o, pəʃˈt̪o, pəçˈt̪o] پښتو "},
            {"Patwin", "Wintun T'ewe"},
            {"Pauna", "Paunaka"},
            {"Pawnee", "paári"},
            {"Paya", "Pech"},
            {"Pazeh", "Pazeh"},
            {"Pemon", "Pemon"},
            {"Pennsylvania German", "Pennsilfaanisch Deitsch Pennsilfaanisch"},
            {"Penobscot", "pαnawαhpskewi"},
            {"Penrhyn", "reo tongareva"},
            {"Persian (Farsi)", "[fɒːɾˈsiː] (fārsi) فارسی"},
            {"Phoenician", "(Dabarīm kanaʿnīm) 𐤃𐤁𐤓𐤉𐤌 𐤊𐤍𐤏𐤍𐤉𐤌"},
            {"Phrygian", "Phrygian"},
            {"Piapoco", "Wenewika"},
            {"Picard", "picard, chti, chtimi, rouchi"},
            {"Piedmontese", "piemontèis"},
            {"Pijin", "Pijin"},
            {"Pilagá", "pit'laxá"},
            {"Pingelapese", "Pingelapese"},
            {"Pintupi", "Pintupi"},
            {"Pinyin", "Àshwəŋnə̀ Pìnyinə"},
            {"Pipil", "Nawat, Náhuat"},
            {"Pirahã", "híaitíihí"},
            {"Pite Sámi", "bidumsámegiella"},
            {"Pitjantjatjara", "Pitjantjatjara"},
            {"Pochuri", "Pochuri"},
            {"Pohnpeian", "Lokaiahn Pohnpei Mahsen en Pohnpei"},
            {"Polci", "Pəlci"},
            {"Polish", "polski [ˈpɔlskʲi] język polski ['jɛ̃w̃zɨk ˈpɔlskʲi] polszczyzna"},
            {"Pomo (Central)", "Pomo"},
            {"Pomo (Eastern)", "Ba·csal [baːʦsal]"},
            {"Pomo (Southeastern)", "X̣awinmfo [χawinmfo]"},
            {"Pomo (Southern)", "Gallinoméro"},
            {"Pontic Greek", "ποντιακά (pontiaká)"},
            {"Poqomam", "Qaq’oral"},
            {"Poqomchiʼ", "Poqomchiʼ"},
            {"Porohanon", "Porohanon"},
            {"Portuguese", "Português [puɾtuˈɣeʃ / poɾtuˈɡes]"},
            {"Potawatomi", "Neshnabémwen"},
            {"Powhatan", "Kikitowämank"},
            {"Proto-Indo-European", "Proto-Indo-European"},
            {"Pukapukan", "Te leo Wale"},
            {"Puluwatese", "Puluwatese"},
            {"Pumi", "prēn mì"},
            {"Punjabi", "ਪੰਜਾਬੀ (panjābī) [pənˈdʒaːbːi], پنجابی"},
            {"Punu", "Yipunu"},
            {"Purepecha", "P'urhépecha"},
            {"Puyuma", "Pinuyumayan"},
            {"Q’anjob’al", "Q’anjob’al"},
            {"Qashqai", "Qaşqay dili, قشقاى ديلى"},
            {"Qatabanic", "Qatabanic"},
            {"Q'eqchi'", "Q'eqchi'"},
            {"Qo Xiong", "Dut Xongb"},
            {"Quapaw", "Okáxpa"},
            {"Quechan", "Kwtsaan [kʷca:n], Kwatsáan Iiyáa"},
            {"Quechua", "Kechua, Runa Simi"},
            {"Quiripi", "Quiripi"},
            {"Rade", "klei Êđê"},
            {"Raga", "Hano"},
            {"Rajasthani", "Rakahanga-Manihiki"},
            {"Rajasthani", "राजस्थानी, راجستھاني (rājasthānī) [ɾɑʤəst̪ʰɑniˑ]"},
            {"Rajbanshi", "राजबंशी (rājabaṁśī)"},
            {"Rama", "rama [rama]"},
            {"Rana", "Rana"},
            {"Rangpuri", "রংপুরী (rôṅgpurī) রাজবংশী (rājôbôṅgshī) কামতাপুরী (kāmôtāpurī) কোচ ৰাজবংশী (koch rājôbôṅgsī) राजबंशी (rājôbôṅgsī)"},
            {"Rapa Nui", "Vananga rapa nui"},
            {"Rarotongan", "Māori"},
            {"Ratahan", "Toratán"},
            {"Ravula", "യേരവാ / ಯೇರವಾ (yēravā) ആദിയാ / ಆದಿಯಾ (ādiyā)"},
            {"Rejang", "Baso Hejang Baso Jang ꤽꥍꤺꥏ"},
            {"Rennellese", "Munggava, Mungiki"},
            {"Réunion Creole", "kréol rénioné"},
            {"Rifian", "Tarifit"},
            {"Rinconada Bikol", "Rinconada Bikol [riŋkonɑːdɑ biːkol] Rinconada [riŋkonɑːdɑ]"},
            {"Ripuarian", "Ripoarėsch"},
            {"Rohingya", "[rʊˈɜiɲɟə] (rwâyṅgya) 𐴌𐴗𐴥𐴝𐴙𐴚𐴒𐴙𐴝 (ruáingga) رُاَينڠَ"},
            {"Romani", "romani ćhib"},
            {"Romanian", "limba română [ˈlimba roˈmɨnə] românește"},
            {"Romániço", "Romániço"},
            {"Romansh", "rumantsch"},
            {"Romblomanon", "Rumblumänon"},
            {"Ronga", "XiRonga"},
            {"Rotokas", "Rotokas"},
            {"Rotuman", "Fäeag Rotuma"},
            {"Roviana", "Roviana"},
            {"Rukai", "Vedrai, Kucapungan Adiri, Kalramomodhesa Kinulan (Budai dialect) Laboa(n) Talamakao (Labuan dialect) Teldrɨka (Maga dialect) ’Oponoho (Mantauran dialect) Taromak (Tanan dialect Kongadavane (Tona dilaect)"},
            {"Rumsen", "Rumšen"},
            {"Rushani", "Rixū̊n ziv"},
            {"Russian", "Русский язык (russkiy yazyk) [ˈruskʲɪj jɪˈzɨk]"},
            {"Rusyn / Ruthenian", "русиньский язык (rusîn'skyj jazyk) русиньска бесїда (ruski jazik)"},
            {"Rutul", "мыхӏабишды‎ (Myḥabišdy) мыхӏабишды чӏел‎ (Myḥabišdy č̣el)"},
            {"Saami / Sámi", "Saami, Sámi"},
            {"Saanich", "SENĆOŦEN, Sənčáθən [sənˈt͡ʃaθən]"},
            {"Saaroa", "Lha’alua"},
            {"Sabaean / Sabaic", "Sabaean, Sabaic"},
            {"Sabanê", "Sabane"},
            {"Sadri", "सादरी / সাদরী / ସାଦରୀ (sādrī / 𑂮𑂰𑂠𑂩𑂲) [sa:dri:], नागपुरी / নাগপুরী / ନାଗପୁରୀ / 𑂢𑂰𑂏𑂣𑂳𑂩𑂲(nagapurī) [na:ɡəpuri:]"},
            {"Safen", "Saafi-Saafi"},
            {"Sahaptin", "Ichishkíin Sɨ́nwit"},
            {"Saint Lucian Creole", "Kwéyòl, Patwa"},
            {"Saisiyat", "SaySiyat [ʃaiʃijat]"},
            {"Sakao", "Laðhi"},
            {"Sakapultek", "Salırça"},
            {"Sakapultek", "Tujaal Tziij [tuχaːl t͡siːχ]"},
            {"Sakizaya", "Sakizaya [sakizaja]"},
            {"Saliba", "Saliba"},
            {"Salish", "Séliš"},
            {"Samaritan Aramaic", "ארמית, Arāmît"},
            {"Samaritan Hebrew", "עברית שומרונית"},
            {"Sambal", "Sambali"},
            {"Samoan", "Gagana fa‘a Sāmoa"},
            {"San Martín Itunyoso Triqui", "Snáhánj nìh [snã˦ʔãh˦ nĩʔ˩]"},
            {"Sandawe", "Sàndàwé kì’ìng [sàndàwékìʔìŋ]"},
            {"Sangirese", "Bahasa Sangihẹ̆"},
            {"Sanglechi", "Sangleči zǝvūk"},
            {"Sango", "yângâ tî sängö"},
            {"Sankethi", "ಸಂಕೇತಿ (saṁkēti) [sankeːt̪i]"},
            {"Sanskrit", "संस्कृत (saṃskṛta) [ˈs̪ɐ̃s̪kr̩t̪ɐ] संस्कृतम् (saṃskṛtam) [ˈs̪ɐ̃s̪kr̩t̪ɐm]"},
            {"Santa / Dongxiang", "Dongxiang kele"},
            {"Santali", "ᱥᱟᱱᱛᱟᱲᱤ (santaṛi) संताली (saṃtālī) সাওঁতালী (sāoṅtālī) ସାନ୍ତାଳୀ (sānttālī)"},
            {"Santiagueño Quechua", "Arhintina runasimi"},
            {"Santo Domingo del Estero Triqui", "Tnánj nình-in"},
            {"Saraiki", "ਸਰਾਇਕੀ / सराइकी / سرائيكى (Sarā'īkī)"},
            {"Saramaccan", "Saamáka"},
            {"Sardinian", "sardu [ˈsaɾdu] sadru [ˈsadɾu] limba sarda [ˈlimba ˈzaɾda] lìngua sarda [ˈliŋɡu.a ˈzaɾda]"},
            {"Sarikoli", "tujik ziv"},
            {"Sarnámi Hindustani", "Sarnaanie Hiendoestaanie"},
            {"Sasak", "Sasak"},
            {"Satawalese", "Satawalese"},
            {"Saurashtra", "ꢱꣃꢬꢵꢰ꣄ꢜ꣄ꢬ ꢩꢵꢰꢵ, சௌராட்டிர மொழி, सौराष्ट्र भाषा (saurāstra bhāśā)"},
            {"Savosavo", "Savosavo"},
            {"Sawi / Savi", "[sɐwiː] (sawī) سَوِى"},
            {"Sayula Popoluca", "yamay ajw tʉcmay-ajw"},
            {"Scots", "Scots Braid Scots Scots Leid Lallans Doric"},
            {"Scottish Gaelic", "Gàidhlig [gaːlɪgʲ] Gàidhlig na h-Alba"},
            {"Secoya", "Paikoka"},
            {"Sedang", "rơtéang"},
            {"Seediq", "Taroko"},
            {"Sekani", "Tse'khene"},
            {"Selkup", "шӧльӄумыт әты (šöľqumyt әty)"},
            {"Sena", "Cisena"},
            {"Seneca", "Onödowá'ga:'"},
            {"Serbian", "српски / srpski [sr̩̂pskiː] српски језик / srpski jezik [sr̩̂pskiː jezik]"},
            {"Serer", "Seereer"},
            {"Seri", "cmiique iitom"},
            {"Serrano", "Maarrênga'twich"},
            {"Seto", "seto kiil'"},
            {"Seychelles Creole", "Seselwa"},
            {"Shabaki", "شَبَكي زِوان (shabaki zuan) "},
            {"Shan", "ၵႂၢမ်းတႆး (Kwam Tai)"},
            {"Shavante / Xavante", "aʼuwẽ mreme"},
            {"Shawiya", "Tacawit, ⵜⴰⵛⴰⵡⵉⵜ"},
            {"Shawnee", "Sawanwa"},
            {"She", "Ho Ne [hɔ˦˦ ne˩˧] Ho Nte"},
            {"Sheko", "S’oku noogu"},
            {"Shenwa", "Haqbaylit̠ [haqbajliθ]"},
            {"Sherpa", "शोर्वि तम्ङे (śorwi tamṅe) [ʃorwi tamŋe] ཤར་པའི་སྐད་ཡིག (shar pa'i skad yig)"},
            {"Shetland(ic)", "Shaetlan"},
            {"Shilha (Tashelhit)", "Tašəlḥiyt, ⵜⴰⵛⵍⵃⵉⵢⵜ"},
            {"Shilluk", "Dhɔg Cɔlɔ"},
            {"Shina", "षीना (Ṣiṇyaá), ݜݨیاٗ"},
            {"Shipibo", "Shipibo"},
            {"Shompen / Shom Peng", "Shom Peng"},
            {"Shona", "chiShona"},
            {"Shor", "шор тили (šor tili) тадар тили (tadar tili)"},
            {"Shoshone", "Sosoni' da̱i̱gwape"},
            {"Shuar", "Shiwar chicham"},
            {"Shughni", "xuǧnůn ziv"},
            {"Shuswap", "Secwepemctsín [səxwəpəmxˈtsin]"},
            {"Siar", "ep warfare anon dat"},
            {"Siberian Tatar", "сыбыр тел (sıbır tel) сыбырца (sıbırca)"},
            {"Sicilian", "lu sicilianu"},
            {"Sierra Leonean Creole", "Krio"},
            {"Sierra Otomi / Highland Otomi", "Yųhų (Eastern Highland Otomi) Ñųhų (Texcatepec / Tenango Otomi)"},
            {"Sikaiana", "Sikaiana"},
            {"Sikkimese", "འབྲས་ལྗོངས་སྐད་ (dranjoke)"},
            {"Silesian", "ślůnsko godka, ślůnski"},
            {"Silt'e", "ስልጥኘ (silt’iñña) [siltʼiɲɲə] የስልጤ አፍ (yasilt’e af) [jəsiltʼe af]"},
            {"Sindhi", "सिन्धी, ਸਿੰਧੀ, 𑈩𑈭𑈴𑈝𑈮, 𑋝𑋡𑋟𑋐𑋢 [ˈsɪndi] سنڌي‎"},
            {"Singlish", "Singlish [siŋlɪsh]"},
            {"Sinhala", "සිංහල (siṁhala) [ˈsiŋɦələ]"},
            {"Sio", "Sio"},
            {"Sipakapense", "Ri Qyolb’al"},
            {"Sirenik", "Сиӷы́ных (siǧynyx) [siˈʁənəx]"},
            {"Sirmauri", "सिरमौरी, 𑚨𑚮𑚤𑚢𑚵𑚤𑚯 (siramaurī) [sɪrəmɔriː]"},
            {"Siwi", "ⴶⵍⴰⵏⵏⵉⵙⵉⵡⴰⵏ, Jlan n isiwan"},
            {"Skolt Sámi", "sääʹmǩiõll [ɕa̟ːmʰc͡çjɘhlː] nuõrttsääʹmǩiõll [nwɘrʰtːɕa̟ːmʰc͡çjɘhlː]"},
            {"Slavey (North)", "Sahtúotʼı̨nę Yatį́"},
            {"Slavey (South)", "Dene Zhatıé, ᑌᓀ ᒐ"},
            {"Slovak", "slovenčina [ˈslɔʋentʂina] slovenský jazyk [ˈslɔʋenski ˈjazik]"},
            {"Slovene / Slovenian", "slovenščina [slɔˈʋèːnʃtʃina] slovenski jezik [slɔˈʋèːnski ˈjɛ̀ːzik]"},
            {"Slovio", "Slovio"},
            {"Soga", "Lusoga"},
            {"Sogdian", "Sogdian"},
            {"Sokoro", "soŋoroŋ"},
            {"Solresol", "Solresol"},
            {"Somali", "af Soomaali, اَف صَومالي˜"},
            {"Somrai", "bii gə chibne"},
            {"Songe", "Kisonge"},
            {"Soninke", "Sooninkanxanne"},
            {"Sonsorolese", "Ramari Dongosaro"},
            {"Sora", "𑃐𑃚𑃝 / ସଉରା (savara)"},
            {"Sorbian (Lower)", "dolnoserbšćina [ˈdɔlnɔˌsɛrskʲi]"},
            {"Sorbian (Upper)", "hornjoserbšćina [ˈhɔʀɲɔˌsɛʀpʃt͡ʃina]"},
            {"South Bolivian Quechua", "Uralan Buliwya runasimi"},
            {"South Picene", "South Picene"},
            {"Southern Ndebele", "isiNdebele"},
            {"Southern Paiute", "Nüwü / Numu"},
            {"Southern Qiang", "Rrmearr"},
            {"Southern Sámi", "Åarjelsaemien gïele"},
            {"Southern Sotho", "seSotho"},
            {"Southern Tiwa", "Isleta"},
            {"Soyot", "сойыт тыл"},
            {"Spanish", "español [espaˈɲol], castillano [kasteˈʎano]"},
            {"Spanish (Mexico)", "español (México)"},
            {"Squamish", "Sḵwx̱wú7mesh sníchim"},
            {"Sranan", "Sranan Tongo"},
            {"Stellingwarfs", "Stellingwarfs"},
            {"Stoney", "Nakoda"},
            {"Sugali", "Sugali"},
            {"Sui", "Suī"},
            {"Sukuma", "Kɪsukuma"},
            {"Sumbawa", "Basa Samawa"},
            {"Sumerian", "𒅴𒂠 (emeg̃ir)"},
            {"Sümi", "Sümi"},
            {"Sundanese", "Basa Sunda, ᮘᮞ ᮞᮥᮔ᮪ᮓ"},
            {"Sunuwar", "कोँइच, Kõits"},
            {"Supyire", "sùpyìré"},
            {"Surigaonon", "Suriganon [suriganon]"},
            {"Suriyani Malayalam", "സുറിയാനി മലയാളം, ܣܘܼܝܲܢܝܼ ܡܲܠܲܝܵܠܲܡ"},
            {"Susu", "Sosoxui"},
            {"Suwawa", "Suwawa"},
            {"Svan", "ლუშნუ ნინ (lušnu nin)"},
            {"Swabian", "Schwäbisch"},
            {"Swahili", "Kiswahili [kiswɑˈhili]"},
            {"Swati/Swazi", "siSwati [sísʷaːtʼi]"},
            {"Swedish", "svenska [ˈsvɛ̂nːska]"},
            {"Swiss German", "Schwiizerdütsch [ˈʃʋitsərˌd̥ytʃ]"},
            {"Sylheti", "ꠍꠤꠟꠐꠤ [silɔʈi] সিলেটি [sileʈi]"},
            {"Syriac", "(leššānā Suryāyā) ܠܫܢܐ ܣܘܪܝܝܐ"},
            {"Taa", "ǃXóõ, Tâa ǂâã"},
            {"Tabassaran", "табасаран чIал"},
            {"Tagabawà", "Tagabawà"},
            {"Tagalog", "Tagalog ᜆᜄᜎᜓᜄ᜔ [tɐˈɡaːloɡ] Wikang Tagalog ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"},
            {"Tagbanwa (Central)", "Tagbanwaᝦᝤᝪᝨᝯ"},
            {"Tahitian", "Reo Tahiti"},
            {"Tahltan", "Tāłtān"},
            {"Tai Dam", "ꪼꪕꪒꪾไทดำ"},
            {"Tai Dón", "Tai Laing (Shan-ni)=တႆးလꧥင်ꩽ (taileng) [tajlɛŋ]"},
            {"Tai Lue", "ᦅᧄᦺᦑᦟᦹᧉ (kam tai lue) [kâm.tâj.lɯ̀]"},
            {"Tai Phake", "ဢႝ ၸႃၵေ [tai pha꞉4 ke꞉5]"},
            {"Tai Ya", "อังกฤษ"},
            {"Taíno", "Taíno"},
            {"Tairoa", "Tairoa"},
            {"Tajik", "тоҷикӣ (tojikī) تجيكى [tɔdʒiˈki]), забо́ни тоҷикӣ́ (zaboni tojikī), форси́и тоҷикӣ́ (forsii tojikī)"},
            {"Takuu", "Takuu"},
            {"Talysh", "tolışə zıvon, толышә зывон, تالشی زَوُن"},
            {"Tamahaq", "Tamahaq"},
            {"Tamang", "तामाङ‎ (tāmāng), རྟ་དམག‎ (tamang)"},
            {"Tamasheq", "Tafaghist"},
            {"Tamazight", "Tamaziɣt, ⵜⴰⵎⴰⵣⵉⵖⵜ"},
            {"Tami", "Tami"},
            {"Tamil", "தமிழ் (tamiḻ) [t̪amiɻ]"},
            {"Tampuan", "Tumpoon, ទំពួន"},
            {"Tanacross", "Nee’aandeg’, Dihtaad Xt’een Aandeg’"},
            {"Tanchangya", "𑄖𑄧𑄐𑄴𑄌𑄧𑄁𑄉𑄴𑄡 / তঞ্চংগ্যা (tawncawṅgg)"},
            {"Tangale", "Tangale"},
            {"Tangkhul Naga", "Luhupa"},
            {"Tangsa (Mossang)", "Muixshvungx"},
            {"Tangut (Xi-Xia)", "𗼇𗟲"},
            {"Tao (Yami)", "Tao"},
            {"Taos", "Taos"},
            {"Tarahumara", "Rarámuri ra'ícha"},
            {"Tariana", "Tariana"},
            {"Tartessian", "Tartessian"},
            {"Tat", "Тати"},
            {"Tatar", "tatarça, татарча, تاتارچا"},
            {"Tausūg", "Bahasa Sūg, بَهَسَ سُوگ"},
            {"Tawallammat Tamajaq", "Tawəlləmmət"},
            {"Tawbuid", "Tawbuid"},
            {"Tayart Tamajeq", "Tamajeq, ⵜⵎⵌⵆ, ثمجق‎"},
            {"Tboli", "Tboli"},
            {"Tedim", "Tidim"},
            {"Tehuelche", "Aonek’o ’á’jen"},
            {"Teino", "Teino"},
            {"Teiwa", "Pitarau"},
            {"Tektitek", "B'a'aj"},
            {"Teleut", "Тэлэңгэт (teleŋget) [tɛlɛŋɡɛt]"},
            {"Telugu", "తెలుగు (telugu) [ˈteluɡu]"},
            {"Tem, Kotokoli", "Tem [tem]"},
            {"Temne", "KʌThemnɛ"},
            {"Temoaya Otomi", "Ñatho [ɲatho]"},
            {"Tepehuán", "O'otham"},
            {"Ter Sámi", "Са̄мь кӣлл, saa'mekiill"},
            {"Terêna", "Terêna"},
            {"Teribe", "Naso"},
            {"Tetum", "Lia-Tetun"},
            {"Thai", "ภาษาไทย (phasa thai) [pʰāːsǎːtʰāj]"},
            {"Thakali", "थकाली (thakālī) [t̪ʰəkali]"},
            {"Thangmi", "थामी (thāmī) [tʱami:]"},
            {"Tibetan (Lhasa)", "དབུས (ü) [wy˧˥˧ʔ/y˧˥˧ʔ] ལྷ་སའི་སྐད་ (lasägä)"},
            {"Ticuna", "Duüxügu"},
            {"Tigre", "ትግረ (tigre) ትግሬ (tigrē) ትግራይት (tigrayit)"},
            {"Tigrinya", "ትግርኛ (tigriññā) [tɨɡrɨɲa]"},
            {"Tii", "Tii"},
            {"Tiipai", "Tiipay"},
            {"Tikopia", "Tikopia"},
            {"Timbisha", "Nümü nangkawih Sosoni nangkawih"},
            {"Tindi", "Идараб мицци (Idarab micci)"},
            {"Tiriyó", "tarëno ijomi"},
            {"Tiruray", "Teduray"},
            {"Tiv", "dzwa Tiv"},
            {"Tiwi", "Tiwi"},
            {"Tlahuitoltepec Mixe", "Ayuujk"},
            {"Tlapanec", "Me̱ꞌpha̱a̱"},
            {"Tłı̨chǫ (Dogrib)", "Tłı̨chǫ Yatıì"},
            {"Tlingit", "Lingít, [ɬìnkítʰ]"},
            {"Toba Qom", "Toba Qom"},
            {"Tobian", "ramarih Hatohobei"},
            {"Tocharian", "Tocharian"},
            {"Tocho", "Tocho"},
            {"Toda", "தோதா (tōtā) 	[t̪oːd̪ɑː]"},
            {"Tofa", "Тоъфа дыл"},
            {"Tojolabal", "Tojolꞌabꞌal"},
            {"Tok Pisin", "Tok Pisin [ˌtok piˈsin]"},
            {"Tokelauan", "Gagana Tokelau"},
            {"Tolai", "Tinata Tuna"},
            {"Tolaki", "To'olaki"},
            {"Tolowa", "Taa-laa-wa Dee-ni' Wee-ya'"},
            {"Tombulu", "Tombulu"},
            {"Tondano", "Toundano"},
            {"Tonga", "Chitonga"},
            {"Tongan", "lea fakatonga [lea fakatoŋa]"},
            {"Tongva / Gabrieliño", "Tongva"},
            {"Tonsawang", "Tonsawang Toundanow"},
            {"Toposa", "ŋatoposa"},
            {"Toqabaqita / To’abaita", "Toqabaqita"},
            {"Toraja-Sa'dan", "basa tora'a"},
            {"Torres-Strait Creole", "Yumplatok"},
            {"Torwali", "توروالى (torwālī)"},
            {"Toto", "তোতো (toto) [toto]"},
            {"Totontepec Mixe", "Ayöök"},
            {"Transylvanian Saxon", "Siweberjesch Såksesch, Såksesch"},
            {"Tsafikí / Colorado", "Tsafikí"},
            {"Tsakhur", "цӀаӀхна миз, c’äxna miz"},
            {"Tsakonian", "τσακώνικα (tsakōnika) [ʧakonika]"},
            {"Tsez / Dido", "цезйас мец (cezyas mec) 	[t͡sɛzˈjas mɛt͡s] цез мец (cez mec) 	[t͡sɛz mɛt͡s]"},
            {"Tshangla", "ཆང་ལོ་ (tshang la) [ʦʰaŋla]"},
            {"Tshiluba / Luba-Kasai", "Tshiluba"},
            {"Tsimshian", "Sm’algya̲x"},
            {"Tsonga", "Xitsonga"},
            {"Tsotsil", "Bats'i k'op"},
            {"Tsou", "Cou"},
            {"Tsuut'ina", "Tsúùt’ínà"},
            {"Tswa", "Xitswa"},
            {"Tswana", "Setswana [sɪtswana]"},
            {"Tucano", "Dahseyé"},
            {"Tujia", "Bifzivsar [pi˧˥ tsi˥ sa˨˩] (Northern Tujia) Mongrzzirhof [mõ˨˩ dzi˨˩ ho˧˥ (Southern Tujia)"},
            {"Tukang Besi", "Tukang Besi"},
            {"Tulu", "ತುಳು‎ (tuḷu) [tuɭu],   ತುಳು ಭಾಷೆ‎ (tuḷu bhāṣe) [tuɭu bʱɒːʂe]"},
            {"Tumak", "bə̀g ɗə təmàgə́ə̀n"},
            {"Tumbuka", "chiTumbuka"},
            {"Tunica", "Luhchi Yoroni"},
            {"Turkana", "ŋa-tùrkwanà / Ng'aturkana"},
            {"Turkish", "Türkçe [ˈtyɾctʃe], Türk dili [ˈtyɾc 'dili]"},
            {"Turkmen", "Türkmen dili (Түркмен дили / تۆرکمن ديلی, [tʏɾkmɛn dɪlɪ],  Türkmençe (Түркменче / تۆرکمنچه, [tʏɾkmɛntʃɛ]"},
            {"Turoyo", "ܛܘܪܝܐ, Ṭûrāyā"},
            {"Tuscarora / Skarohreh", "Ska꞉rù꞉ręʼ [skɔːruːrə̃ʔ]"},
            {"Tutchone", "Dän k'í, Dän k'è"},
            {"Tutelo", "Tutelo"},
            {"Tuvaluan", "Te Ggana Tuuvalu"},
            {"Tuvan", "тыва дыл (tıva dıl) [tʰɯˈʋa tɯl]"},
            {"Twi / Akan Kasa", "Twi"},
            {"Tzeltal", "Batz'il K'op"},
            {"Tz'utujil", "Batz'il K'op"},
            {"Ubang", "Ubang"},
            {"Ubir", "Ubir"},
            {"Ubykh", "Твaҳəбзa (Twaxəbza)"},
            {"Udege", "Удиэ (udie) [udie]"},
            {"Udi", "удин муз, udin muz"},
            {"Udmurt", "удмурт кыл (udmurt kyl) [udmurt kyl]"},
            {"Uduk", "ʼTwāmpā"},
            {"Ugaritic", "Ugaritic"},
            {"Ukrainian", "українська мова (ukrayins'ka mova)"},
            {"Ulch", "Нāн'и хэсэни (Nān’i hėsėhi) [naːnəi xəːsəːxi]"},
            {"Ulithian", "Yulidiy"},
            {"Umatilla", "Tamalúut"},
            {"Umbrian", "Umbrian"},
            {"Umbundu", "Úmbúndú"},
            {"Ume Sámi", "Ubmejensámien giella"},
            {"Umiray Dumaget", "Umiray Dumaget"},
            {"Unami (Lenape)", "Unami"},
            {"Upper Kuskokwim", "Dinakʼi"},
            {"Upper Tanana", "Neeʼaandeegnʼ"},
            {"Urarina", "Oruarinya"},
            {"Urdu", "[ˈuːrdu] (urdū) اُردُو"},
            {"Uropi", "Uropi"},
            {"Urum", "Урум (Urum)"},
            {"Uspantek", "Uspanteko"},
            {"Uyghur", "[ujɣur tili] Уйғур тил, Uyghur tili, ئۇيغۇرچە"},
            {"Uzbek", "Ўзбек тили, O'zbek tili, أۇزبېك ﺗﻴﻠی"},
            {"Vadi", "TsuVaɗi"},
            {"Vaeakau-Taumako", "Vaeakau-Taumako"},
            {"Vai", "ꕙꔤ (vai) [vai]"},
            {"Valenican", "valencià [valensiˈa]"},
            {"Värmlandic", "Värmländska"},
            {"Venda", "Tshivenḓa, Luvenḓa"},
            {"Venetian", "vèneto"},
            {"Veps", "vepsän kel’"},
            {"Vietnamese", "Tiếng Việt (㗂越) [tǐəŋ vìəˀt / tǐəŋ jìək]"},
            {"Volapük", "Volapük  [volaˈpyk]"},
            {"Võro", "võro kiilʼ"},
            {"Votic", "vad’d’a tšeeli mā tšeeli"},
            {"Vurës", "Vurës"},
            {"Wa", "Va"},
            {"Waama", "Waama"},
            {"Wa'di", "Wa'di"},
            {"Wakhi", "x̌ik zik х̆ик зик"},
            {"Walla Walla", "Waluulapan"},
            {"Wallisian", "Fakaʻuvea"},
            {"Walloon", "walon"},
            {"Wambaya", "Wambaya"},
            {"Wambule", "वाम्बुले (wāmbule) [vaːmbule]"},
            {"Wancho", "वांचो (wangco) [waŋʧɔ]"},
            {"Wandamen", "Wondama"},
            {"Wanetsi", "(waṇecī) وڼېڅي"},
            {"Wantoat", "Taap"},
            {"Waray-Waray", "Waray-Waray"},
            {"Wardaman", "Wardaman"},
            {"Warlpiri", "Warlpiri"},
            {"Washo", "wá:šiw ʔítlu"},
            {"Wayana", "Wayana"},
            {"Wayuu", "Wayuunaiki"},
            {"Welsh", "Cymraeg [kəmˈrai̯ɡ / kəmˈraːɡ / kʊmˈraːɡ]"},
            {"Wemba Wemba", "Wemba Wemba"},
            {"West Polesian", "заходышнополіська волода (zakhodyshnopoliska voloda)"},
            {"Western Fijian", "Nadrogaa"},
            {"Western Neo-Aramaic", "[ˈsɨ:ryɒn] (sūryān) ܐܪܡܝܐ"},
            {"Western Pwo (Karen)", "ဖျိၩ့ (phloʔng) ဖျိၩ့ၡိ  (phloʔngśo)"},
            {"Western Rote", "Dela-Oenale"},
            {"Western Subanon", "Sinubanon"},
            {"Western Yugur", "yoɣïr lar, yoɣïr śoz"},
            {"Wichita", "Kirikir’iis, Kirikirʔi:s"},
            {"Wik-Mungkan", "Wik-Mungkan"},
            {"Wintu", "winthu:h"},
            {"Wiradjuri", "Wirraayjuurray Wirraaydhuurray"},
            {"Wolaytta", "Ometo"},
            {"Woleaian", "Woleaian"},
            {"Wolio", "Wolio"},
            {"Wolof", "wolof [wɔlɔf] ولوفل"},
            {"Wukchumni", "Wukchumni"},
            {"Wyandot (Huron)", "Waⁿdat"},
            {"Wymysorys", "Wymysiöeryś"},
            {"Xamtanga", "ኃምታጛ (χamtaŋa) [ˈχamtaŋa]"},
            {"Xârâcùù", "Xârâcùù"},
            {"Xhosa", "isiXhosa [isiˈǁʰɔsa]"},
            {"Xibe", "ᠰᡞᠪᡝ ᡤᡞᠰᡠᠨ (sibe gisun)"},
            {"Yabem", "Jabêm"},
            {"Yaeyama", "ヤイマムニ, 八重山物言 (yaimamuni) [jaimamuni]"},
            {"Yaghan", "Háusi Kúta"},
            {"Yaghnobi", "yaɣnobī́ zivók яғнобӣ зивок"},
            {"Yagua", "Nijyamïï Nikyejaada"},
            {"Yakama", "Ichishkíin / Mámachatpam"},
            {"Yakan", "Yakan"},
            {"Yakkha", "याक्खा (yākkhā)"},
            {"Yakut (Sakha)", "саха тыла‎ (saxa tıla) [saxa tɯla] сахалыы‎ (saqalıı) [saxalɯː]"},
            {"Yaminawa", "Yaminahua"},
            {"Yanesha'", "Yaneshac̈h"},
            {"Yang Zhuang", "Káang Thó"},
            {"Yao", "chiYao"},
            {"Yapese", "Waab"},
            {"Yaqui", "Yoem Noki"},
            {"Yawuru", "Yawuru [jaoɹo]"},
            {"Yazghulami", "Йузда̄ми зәвәг, Yuzdāmi zәvәg"},
            {"Ye’kuana", "Ye’kuana [jeʔkwana]"},
            {"Yemba", "Yɛmba, Dschang"},
            {"Yerukula", "ஏறுகள / ఎఱుకల"},
            {"Yevanic", "γεβανί γλώσσα (yevani glosa) יעואני גלוסא"},
            {"Yi", "ꆈꌠ꒿, Nuosuhxop"},
            {"Yiddish", "[ˈ(j)ɪdɪʃ] (yidish / idish) ייִדיש, יידיש or  (yidish-taytsh) ייִדיש-טײַטש (mame-loshn) מאַמע־לשון"},
            {"Yidgha", "یدغہ (yidgha)"},
            {"Yimchungrü", "Yimchungrü"},
            {"Yindjibarndi", "Indjibandi"},
            {"Yocoboué Dida", "Dída [di˥da˧]"},
            {"Yogad", "Yogad [joɡad]"},
            {"Yola", "Yola Taalke"},
            {"Yolmo", "Yolmo (ह्योल्मो)"},
            {"Yolŋu", "Yolŋu matha"},
            {"Yonaguni", "ドゥナンムヌイ, 与那国物言 (Dunan Munui) [dunaŋmunui]"},
            {"Yoron", "ユンヌフトゥバ (yunnu futuba) [⸢ju⸣nnu ⸢fu⸣tuba]"},
            {"Yoruba", "Èdè Yorùbá [e˩de˩ joru˩ba˥]"},
            {"Yucatec Maya", "Màaya t'àan"},
            {"Yuchi/Euchee", "yUdjEha"},
            {"Yucuna", "Jukuna"},
            {"Yukaghir (Northern / Tundra)", "Вадул аруу (Wadul aruu) [wadul aruː]"},
            {"Yukaghir (Southern / Forest)", "Одул (Odul) [odul]"},
            {"Yukpa", "Yukpa [jukpa]"},
            {"Yup'ik (Central Alaskan)", "Yugtun, Cugtun"},
            {"Yupik (Central Siberian)", "Юпик (jupik) [jupik]"},
            {"Yurok", "Puliklah"},
            {"Zaghawa", "Beria"},
            {"Záparo", "Záparo"},
            {"Zapotec (Choápam)", "Diꞌidzaꞌ xidzaꞌ"},
            {"Zapotec (Güilá)", "Diza"},
            {"Zapotec (Isthmus)", "Diidxazá [dìdʒàˈzà]"},
            {"Zapotec (Miahuatlán)", "Diiste"},
            {"Zapotec (Rincón)", "Didza Xidza"},
            {"Zapotec (San Dionisio Ocotepec)", "Diza"},
            {"Zapotec (Zoogocho)", "Diža'xon [diʒaʔˈʐon]"},
            {"Zarma", "Zarmaciine"},
            {"Zaza", "Zazakî / Kirmanckî / Kirdkî / Dimilkî, زازاکی"},
            {"Zeelandic", "Zeêuws"},
            {"Zenaga", "Tuẓẓungiyya"},
            {"Zhuang", "Vahcuengh, Vaƅcueŋƅ, 話僮"},
            {"Zigula", "Chizigua"},
            {"Zinza", "Ecizinza"},
            {"Zou / Zo", "Zokam"},
            {"Zulu", "isiZulu [isízṳːlu]"},
            {"Zuni / Zuñi", "Shiwi'ma"},
            {"Zuwara Berber", "Maziɣ, ⵎⴰⵣⵉⵗ" },
            {"Karen(S'gaw)", "ကညီကျိာ် (k'ñòklọ) [kʔɲɔklo˩ˀ]"},
            #endregion NativeNames
        };
    }
}
